### ISSUE TITLE
Block of Iron

### ISSUE THREAD

**Issue by Maycke25** [WanionCane/UniDict#1]
Hello, I updated the Unidict to UniDict-1.7.10-2.7 and I can no longer do "Block of Iron". perhaps the recipe was removed.
I went back to UniDict-1.7.10-2.6 version and can make the "Block of Iron"

Ola, eu atualizei o Unidict para UniDict-1.7.10-2.7 e não consigo mais fazer "Bloco de Ferro". talvez a receita foi removida. 
eu voltei pra versão UniDict-1.7.10-2.6 e consigo fazer o "bloco de ferro"

**Comment by WanionCane** [comment]
hi! you are brazilian or portuguese or some other country? nice to meet you !
after i took a look on it, apparently i forgot to do one checking, i will pay more attention to this on the future.
sorry about this problem.

olá! você brasileiro ou português ou algum outro país? prazer te conhecer!
depois de dar uma olhada, aparentemente eu esqueci de fazer uma verificação, vou prestar mais atenção a isso no futuro.
desculpe por esse problema..

**1.9.4**
[af47d898920144f526058d959658f0381ddeb18f](https://github.com/WanionCane/UniDict/commit/af47d898920144f526058d959658f0381ddeb18f)

**1.7.10**
[fca07bdb881aa2431738f80182b58855ba6d699b](https://github.com/WanionCane/UniDict/commit/fca07bdb881aa2431738f80182b58855ba6d699b)

**Comment by Maycke25** [comment]
brasileiro.

**Comment by WanionCane** [comment]
então não é nessessario falar inglês por aqui, :P
testou com a nova versão, funcionou?

**Comment by Maycke25** [comment]
Opa, testei agora.. ta funcionando. meu nick no curse é o mesmo daqui se quiser add pra jogar qlq hora

**Comment by WanionCane** [comment]
adiciono sim =p, vou fechar o tópico, ok?
