### ISSUE TITLE
[Feature Request] Block Drops

### ISSUE THREAD

**Issue by sscards55** [WanionCane/UniDict#10]
This is probably outside the scope of this mod but I was wondering.
Could make it so that when you pick up an ore it would turn into one of the owners ore.

I can only think of three examples for this.
1. Using a forestry backpack so that all the slots are not used up. It applies to a other inventories too.
2. When you want to add it into a pack that has a mod that gives you ores.(HQM)
3. When adding this to a pack where a modpack maker was too lazy to properly configure world generation, i.e., me.

**Comment by WanionCane** [comment]
It is a good feature, but I don't know if I should implement it, since OreGen Integration is coming =)

edit: not exactly coming, but it is planned =p
