### ISSUE TITLE
(1.12.2) IE Crusher: Certain Items Missing Secondary Outputs

### ISSUE THREAD

**Issue by TechnoMysterio** [WanionCane/UniDict#101]
Immersive Engineering's crusher is lacking certain secondary outputs for items. For instance, iron ore is missing nickel grit as a secondary output, sandstone is missing sulphur, and copper is missing gold grit. I understand this issue has been solved in the past, but it seems to have returned.

UniDict: 2.5e
Forge: 14.23.4.2729
MC: 1.12.2

**Comment by WanionCane** [comment]
[fixed](https://minecraft.curseforge.com/projects/unidict/files/2581238) =D
