### ISSUE TITLE
[Suggestion] Unify Coal Coke and Slag

### ISSUE THREAD

**Issue by axieum** [WanionCane/UniDict#102]
I think it would be great to be able to unify the Coal Coke (dust, fuel and fuelBlock) types, as well as the slag (item, crystal) types; and also have these changes reflected in the recipes too.

This is also in relation to issue #85.

**Comment by WanionCane** [comment]
sorry for the huge delay =/

it may already be possible, checkout `S:customUnifiedResources` on the .cfg file.

**Comment by axieum** [comment]
Yes, using that config property will successfully unify the type **in JEI**, but will not reflect the recipe changes for Immersive Engineering for example. I believe it only changes machine recipes if the item is a metal?

Thanks in advance.
