### ISSUE TITLE
Crash with newShapelessRecipeTemplate

### ISSUE THREAD

**Issue by Blatts12** [WanionCane/UniDict#103]
Crash:
https://paste.dimdev.org/fativalaze.mccrash

Script:
https://paste.dimdev.org/ufeyocihug.cs

**Comment by WanionCane** [comment]
sorry for the huge delay =/

you can't pass anything that isn't a string to it, so by removing `iron` and `hammer` it may work.
but, passing defined items and ore dict entries is a really cool idea, and I may implement it on the future =)

thanks a lot! =D

for now, I will close this.
