### ISSUE TITLE
[Question] Add other OreDict entries to UniDict

### ISSUE THREAD

**Issue by 016Nojr** [WanionCane/UniDict#104]
Is it possible at the moment to add other OreDict entries to UniDict for it to unify? With one of CoFH's latest features it added "pigments" which is basically CoFH dyes, using the same ore dictionary as the normal dyes, so I am left with Minecraft's dyes and CoFH's dyes (pigments).

How would I make UniDict unify these types of dyes so I am left with dyes from one of them?

**Comment by WanionCane** [comment]
sorry for the huge delay =/

it may be possible, but it may be time consuming, checkout `S:customUnifiedResources` on the .cfg file.
