### ISSUE TITLE
Thermal Expansion gear recipes that do not work. 

### ISSUE THREAD

**Issue by Darkfiend009** [WanionCane/UniDict#106]
![image](https://user-images.githubusercontent.com/42146629/43722264-dde76814-9962-11e8-8b28-9a8aeb727821.png)

I've run into gear recipe issues regarding UniDict and the Thermal Expansion mod. I haven't been able to test all of the gears, but the ones i have tested seem to have recipes that do not work.

For the Tin gear above, if i replace the copper ingot with an iron ingot, the recipe works. There are similar workarounds for the other gears as well.

I'm pretty new to all of this, so excuse my ignorance if this is an easy fix i am unaware of. If there is anything additional i need to provide, please just let me know.

**Comment by WanionCane** [comment]
super weird, I will take a look.

**Comment by WanionCane** [comment]
I couldn't find any broken recipe, if you are playing on a server, be sure to check if both client and server have the same configs, and mods.
