### ISSUE TITLE
[Suggestion] Liquid unification?

### ISSUE THREAD

**Issue by axieum** [WanionCane/UniDict#107]
Is there any chances that liquids could be unified?

E.g. Thermal Expansion's Essence of Knowledge is equivalent to other mods Liquid XP.

**Comment by EngineerXL** [comment]
It'd be nice to see fluid and gas unification. E.g. mod can setup recipes throught Boilers and setup only one steam, only one distilled water, only one Deiterium and Tritium

**Comment by WanionCane** [comment]
no, this would need a completely new mod.
