### ISSUE TITLE
Request 1.10.2 - Can you add simple ores and Silent Gems support?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [WanionCane/UniDict#11]
The title says it all!

**Comment by WanionCane** [comment]
sorry for the delay, In which way this mod requires an integration?

**Comment by P3rf3ctXZer0** [comment]
the ores and gems. It has tin and copper ores and an iron equivalent.

**Comment by WanionCane** [comment]
not all mods that adds ingots or gems requires an integration, usually, only mods that adds some sort of ore processing requires an integration.
this is the case for Simple Ores? does it add some kind of ore processing?

**Comment by P3rf3ctXZer0** [comment]
Yeah; for sure Silent Gems Does. I am also pretty sure that Simple ores does as well.

**Comment by JohnC94** [comment]
Do either of these mods have processing machines? If all you are trying to do is unify items then UniDict can already do that. What exactly do you want UniDict to do that it isn't doing for you?

**Comment by P3rf3ctXZer0** [comment]
I thought UniDict makes it so you get the equivalent of whatever another material is.

**Comment by JohnC94** [comment]
UniDict "unifies" different resources. For example, if you have Forestry copper ore and Immersive Engineering copper ore, depending on the machines that you process those ores with you will end up with a copper ingot from Forestry, one from Immersive Engineering or one from a different mod like Tinker's Construct. UniDict can make it so that any time you process copper ore you will end up with only one type of copper ingot.

**Comment by P3rf3ctXZer0** [comment]
Okay so yes Simple ore has copper and tin ore. So does Silent Gems. Well I am just letting you know. If you want to or not add support its not life or death XD

**Comment by WanionCane** [comment]
sorry for the delay =/
I am not having a lot of time lately
so, just by having copper, and tin, isn't enough for an integration, but I will take a deep look on it on the next few days.
thanks.

**Comment by WanionCane** [comment]
since there is no reason to create an integration with this mod, I am closing this.
