### ISSUE TITLE
[Feature] - Support for GalacticCraft

### ISSUE THREAD

**Issue by mrhackcz** [WanionCane/UniDict#110]
Hello Wanion 👍
Im, looking for galacticCraft support, can you take a look for that? :))

**Comment by ShaytoriousD** [comment]
Hi also from me, i am just in the process of making a modpack for myself and would also like it if you could add support for galacticraft. 
that would be great thanks Wanion :)

**Comment by WanionCane** [comment]
no promises guys, but I will take a look =P (next week)

**Comment by WanionCane** [comment]
so.. after awhile, I took a look, but, I couldn't find any reason to create an Integrationb with GalactiCraft.
