### ISSUE TITLE
IC2, Mekanism, Project red, galacticraft

### ISSUE THREAD

**Issue by ShaytoriousD** [WanionCane/UniDict#111]
Hi, i just installed this on my modpack im building but as i have so many mods its hard to get them all to play nice, if you could take a look and maybe help me ? i have 4 types of copper ingot and a few tin ingots, I know ic2 and mekanism are on your list but one copper ore is from mek and one from ic2 then one from p-red and one from galacticraft. heres my modpack to try yourself, just bear in mind so far iv only thrown all the mods i want in and got it to run i havnt tweaked it all yet.... hence installing this, so if poss can you add p-red and galacticraft pls  thanks.
https://www.dropbox.com/s/89vais84pbupdyk/ShaytoriousD-modpack.zip?dl=0

**Comment by WanionCane** [comment]
well. IC2 and Mekanism are already supported, but, I will have to take a look on Project Red and Galacticraft.

**Comment by SlayerTheChikken** [comment]
Galacticraft integration status? I can't make it override for copper, tin, or aluminum if needed.

**Comment by ElektroKill** [comment]
I don’t see a reason for galacticraft support
