### ISSUE TITLE
Allow Oredict to be used instead of strings in the Unidict crafttweaker scripts.

### ISSUE THREAD

**Issue by Peach774** [WanionCane/UniDict#112]
I am trying to add plates, but the "gem" string doesn't work for most things because most of the ore dict gem items dont actually have gem in their names.

**Comment by WanionCane** [comment]
I am planning to allow OreDict, and as well fixed Itemstacks, but for now, I almost have no time to do it, but probably next week I will take a better look on this possibility =P

**Comment by WanionCane** [comment]
done! =P
