### ISSUE TITLE
Immersive Engineering Crusher and CraftTweaker recipes cleaned up by UniDict

### ISSUE THREAD

**Issue by squid-box** [WanionCane/UniDict#114]
As described in https://github.com/BluSunrize/ImmersiveEngineering/issues/3206 :

Trying to add recipes to the Immersive Engineering Crusher with the same output (eg. output 4 `minecraft:clay_ball` from both `minecraft:clay` and `minecraft:hardened_clay`) will result in just having one of the recipes available.

According to **malte0811** this is due to UniDict cleanup:

> I looked at their code, they seem to be "cleaning up" the crusher recipes in a way that looks like it may well cause issues (e.g. assuming that 2 recipes are the same when a specific hash is the same.

### Versions
**Minecraft**: 1.12.2
**UniDict**: 1.12.2-2.7b
**WanionLib**: 1.12.2-1.5
**ImmersiveEngineering**: 0.12-85

Example CraftTweaker recipes for testing:

```
mods.immersiveengineering.Crusher.addRecipe(<minecraft:clay_ball>*4, <minecraft:clay>, 3600);
mods.immersiveengineering.Crusher.addRecipe(<minecraft:clay_ball>*4, <minecraft:hardened_clay>, 4000);
```

**Comment by WanionCane** [comment]
hello, so, I added a config to disable the duplicate check & removal =P

**Comment by squid-box** [comment]
A quick test with UniDict-1.12.2-2.8 with the same setup as I reported with looks to work perfectly.
Thanks for doing this so quickly!

_Edit: I don't know much about the inner workings of this, so take this with a grain of salt, but it's working with the default setting of `B:ieIntegrationDuplicateRemoval=true`. As I read this shouldn't I be setting that to false to get around the problem?_ 😕 

_Either way, it works and I won't fuss about it._
