### ISSUE TITLE
Immersive Engineering/Crafttweaker/Crusher

### ISSUE THREAD

**Issue by Greatone123** [WanionCane/UniDict#117]
Greetings, 

I'm currently trying to add some simple recipes to my crusher in IE, and I've got some strange issues.

My Crafttweaker script ([https://pastebin.com/vqp7bWDp](https://pastebin.com/vqp7bWDp)) 
The script works fine, until UniDict is installed. With UniDict, ONLY the first recipe works. So in the case of the script I have in the pastebin, the Iron Chest Piece is the only one that works. It's the only one that shows up in JEI, and it's the only one that the crusher will process. I had a much larger script that I use on the server, but adding those recipes disabled the entire script, so I separated it for testing.

The crafttweaker log file ([https://pastebin.com/mWnFZ0QZ](https://pastebin.com/mWnFZ0QZ
))

Any recommendation rather than just disabling IE support in the config? I like UniDict and what it does, but I'm trying to make my server some unique recipes that my players will appreciate.

Thanks for any help.

Forge-14.23.5.2770
IE-0.12-86
CT-4.1.11
TF-2.6.1.22
UD-2.9.1

**Comment by idnthvn** [comment]
I have a similar issue.   But mine is removing plate recipes from the Metal Press with Immersive engineering.   Unidict does recipe changes PostInt. Versus crafttweaker does it PreInt.   I have to disabke the integrstion for IE in order for crafttweaker to do its thing.   I also have to do this for Thermal Expansion as well.
At this moment.   I chose to disable.   I know there is a rumor of things changing for 1.13.2 but thats all i know

**Comment by ElektroKill** [comment]
Hello, sorry for the 2-year late response...

This was a bug in the integration for the crusher which was caused by the fact that UniDict only used the OreDictionary input property which is null in the case of your tools, this threw off the duplicate removal as input(null) and output(pulverized iron) was the same. This will be fixed in the upcoming 3.0.6 release.
