### ISSUE TITLE
UniDict causes Crashes on my server

### ISSUE THREAD

**Issue by LumiakLeBorgne** [WanionCane/UniDict#118]
I realized a modpack where I put UniDict, but when I start my server, it crashed.
It only hapen with UniDict into it !
Here is the crash log
[https://pastebin.com/njfK4zCG](url)
Thanks !

**Comment by WanionCane** [comment]
I took a look, and there are two possibilities for this:
your java is outdated, or, UniDict `.jar` is corrupted.
