### ISSUE TITLE
Help with config: Setting global owner

### ISSUE THREAD

**Issue by SpartanSamuel** [WanionCane/UniDict#12]
I love your mod, but I'm having some difficulties setting the global owner for specific metals.
In my case I'm working with Industrial Craft 2, Immersive Engineering, Forestry, and Railcraft. I'd like RC to take precedence for all metals except Uranium (which is fine because RC doesn't gen uranium). For Uranium, I'd like IC2 to take over.

Now, in your config I've tried setting S:ownerOfEverything to

minecraft
railcraft
ic2

but all of my copper comes out as IC2 instead of RC. I've tried reversing the list but get the same result.

Maybe what I'm looking for is in B:enableSpecificKindSort, but I don't know how the syntax should work as there are no examples in the config.

Could you help me, please?

**Comment by WanionCane** [comment]
I will take a look

**Comment by WanionCane** [comment]
oh, hey, about the lack of examples, once you enable it, UniDict will generate a guide file.
config\unidict\jsonFormatGuide.txt

**Comment by WanionCane** [comment]
I found the problem =/
I am going to release a fix for it soon.
thanks for the report =p

**Comment by SpartanSamuel** [comment]
Speaking of config files, there's a unidict.cfg in the base config folder (v 2.4) and then another one in the config/unidict folder (v2.5). I was making all of my changes to the 2.4 one, should I move my changes to the 2.5 one and delete the 2.4?

**Comment by SpartanSamuel** [comment]
Hey, yeah that absolutely turned out to be the issue in my case! I deleted the 2.4 config, adjusted 2.5 appropriately and voila. RC-based ingots and blocks.

**Comment by WanionCane** [comment]
good to know that everything is now working =D

**Comment by kragnoth** [comment]
side note, none of my ore are unifying after smelting after latest update.  reverting to latest release fixes it.  Will attempt deleting config and testing different methods to test this.

**Comment by WanionCane** [comment]
UniDict.cfg was moved to config/unidict folder, please configure it. I hope it works. if it doesn't, please report here.

**Comment by WanionCane** [comment]
hey @kragnoth, you are right, after taking a look I indeed can confirm that furnace integration is broken =/

**Comment by WanionCane** [comment]
hey @kragnoth could you try [this](https://minecraft.curseforge.com/projects/unidict/files/2365895)? I hope it can fix your issue.

**Comment by kragnoth** [comment]
Cheers, I've got to go downtown to grab some tools, but I've updated my server and will let you know if it works out with the new version.  I have plenty of ores stored to test this with when I get back.

**Comment by kragnoth** [comment]
Looks like it fixed the issue.  Applied newest update and its working again.  Thank you for your wonderful mod.

**Comment by WanionCane** [comment]
@kragnoth yay, thanks! =P
