### ISSUE TITLE
Crash with latest WanionLib

### ISSUE THREAD

**Issue by Pilad** [WanionCane/UniDict#120]
Crash with latest  WanionLib-1.12.2-1.6

**Comment by SpudGunMcGee** [comment]
Posting like this doesn't help anyone fix the issue. Try to explain what is happening, post a crash report. Otherwise don't bother...

**Comment by Pilad** [comment]
Ok. https://pastebin.com/KBd7LkCf

**Comment by Pilad** [comment]
FML: MCP 9.42 Powered by Forge 14.23.5.2768 , why 2772?

**Comment by SpudGunMcGee** [comment]
Because that was the version of forge I was using at the time?

**Comment by WanionCane** [comment]
sorry guys.. https://github.com/WanionCane/WanionLib/issues/7
please update to the lastest WanionLib
[WanionLib-1.12.2-1.7.jar](https://minecraft.curseforge.com/projects/wanionlib/files/2632700)
