### ISSUE TITLE
Crashing on Forge 12.23.5.2772

### ISSUE THREAD

**Issue by SpudGunMcGee** [WanionCane/UniDict#121]
### Description
Unidict causes crashes on the latest version of forge. Unsure as to why. I believe #120 is the same issue but no info was provided.

### How to replicate -
Create a MC 1.12.2 Instance
Install Forge 14.23.5.2772
Install just Unidict 2.9.1 and WanionLib 1.6
Run and Crash

### Crash Report -
https://gist.github.com/SpudGunMcGee/4ed91baf195ad1b5b6fa6c20294ed110

**Comment by SpudGunMcGee** [comment]
Look like #120 was right, downgrading to WanionLib 1.5 fixes the issue for now.

**Comment by WanionCane** [comment]
https://github.com/WanionCane/WanionLib/issues/7
please update to the lastest WanionLib
[WanionLib-1.12.2-1.7.jar](https://minecraft.curseforge.com/projects/wanionlib/files/2632700)

**Comment by SpudGunMcGee** [comment]
Cheers
