### ISSUE TITLE
[Suggestion] UniDict generated chest loot.

### ISSUE THREAD

**Issue by LumberWizard** [WanionCane/UniDict#122]
When loot is being generated in a dungeon chest or any other sort of loot chest, it would be nice to have its loot automatically swapped to the UniDict preferred variety, so I don't get 6 different types of copper in a loot chest. (This is the only thing preventing me from deleting InstantUnify in my pack).

**Comment by WanionCane** [comment]
sorry for the ULTRA late reply, this is kinda complicated to do, this is why I haven't done it yet.

**Comment by ElektroKill** [comment]
Due to how loot tables are handled, this is not possible. Sorry!
