### ISSUE TITLE
easy iron plate recipe

### ISSUE THREAD

**Issue by TheNimbleNinja** [WanionCane/UniDict#123]
there is an easy iron plate recipe that takes 4 iron to make 4 plates and i do not want this and i cant seem to get rid of this recipe can you help me remove it

**Comment by WanionCane** [comment]
UniDict does not create previous unexisting recipes, so, if this recipe is being created, it had to exist earlier.
so, you can turn off Crafting Integration to check the recipe original name, and with the original name, remove it using CraftTweaker, or you can remove it using UniDict own config to remove recipes. `S:recipeToRemoveList`

**Comment by 0xlsca** [comment]
I have identified UniDict to add the following recipe:

![image](https://user-images.githubusercontent.com/24982216/65511585-d25a9f00-ded7-11e9-9a13-d8c57568f9cd.png)

The causing recipe ID is `unidict:plateiron_x3_shape.aaa`

Adding the ID under `S:recipeToRemoveList` did not work.

I can confirm that the recipe is not present when disabling the UniDic crafting entry in `IntegrationModule.cfg`.

So far, I am out of options in regards of removing the recipe and could use some help with it.
@WanionCane

**Comment by nathanvoglsam** [comment]
I am also experiencing the exact issue @TomConnery is on the latest version provided through curseforge. Disabling `B:Crafting` removes the recipe from the list and I can't remove it through CraftTweaker or through the `S:recipeToRemoveList` config option.

**Comment by nathanvoglsam** [comment]
Found the solution to being able to remove the recipe.

There needs to be 6 spaces after the `aaa` in `unidict:plateiron_x3_shape.aaa` and it must be wrapped in brackets. The spaces represent an empty item in the crafting grid while still generating a unique name.

This issue #94 is where I found the solution as it clearly shows the spaces in the recipe names.

Perhaps this should be documented somewhere?

_EDIT: Referenced the wrong issue_

**Comment by ElektroKill** [comment]
Looks like this is solved!

**Comment by VerySaltyOreos** [comment]
Had this exact same problem and was confused for half an hour until I figured out the line should look like this.

S:recipeToRemoveList <
    unidict:"plateiron_x3_shape.aaa      "
     >
     
     Maybe I'm just dumb, because I didn't understand where the brackets went and kept doing 
     
     S:recipeToRemoveList <
    "unidict:plateiron_x3_shape.aaa      "
     >
     
     Which would make the game unable to launch.
