### ISSUE TITLE
Ores to Dust in Mekanism Enrichment Chamber doesn't work with Unidict

### ISSUE THREAD

**Issue by Fireztonez** [WanionCane/UniDict#127]
Hello,
When I enabled the Mekanism integration in Unidict, the enrishment chamber can't make dusts from ores anymore. So, look like Unidict remove all the recipe for Ores to dusts, but doesn't add-it back...

Can you look to fix that, because this is pretty anoying to not be able to do what it should with that machine.

The configs I have for unidict is:
https://gist.github.com/Fireztonez/001a7360aefdde37cc7de04cfaee10ab

Version:
Unidict: 2.9.2
Minecraft Forge: 1.12.2 - 14.23.5.2796
Mekanism: 9.4.13.349

Thank's
Fireztonez

**Comment by WanionCane** [comment]
weird, I will take a look here =P

**Comment by Fireztonez** [comment]
Do you have time to look about this issue?

I finally fond something when I look for Dusts recipe in the Enrichment Chamber, but this is still an issue... So, here the screen of the recipes, availiable in JEI for Copper Dusts:
![ores_enrishment_chamber_issue](https://user-images.githubusercontent.com/19277301/51011699-7f96ae00-1527-11e9-9444-eb0ad991d25b.png)

Basically, I think what's apen is, when Unidict unify everithing, it remove all recipes for the Copper Dust and add back only one recipe with the fist Copper Ore in the unification, but I specially ask to don't unify Ores, because I want to have Immersive Engineering Metals and Dusts, but the Immersive Engineering OreGen in disabled and I use only the ores from Thermal Foundation or Nuclearcraft (only for Uranium, boron, Magnesium and Lithium)...

I know mekanism doesn't accept Oredict Entry with the crafttweaker integration for the enrishment chamber, so, I don't know if this is the caused of this issue with the unification with Unidict??

**Comment by Fireztonez** [comment]
I just fond others issues, again link with that same problem...

Somes dusts recipes is show in JEI, but doesn't really work into the Enrichment Chamber. I have 2 different examples for you:
![enrichment_chamber_jei_prob](https://user-images.githubusercontent.com/19277301/51012610-051c5d00-152c-11e9-9146-94745d46c236.png)
![enrichment_chamber_jei_prob2](https://user-images.githubusercontent.com/19277301/51012611-051c5d00-152c-11e9-99a8-a383e5b63467.png)

Both show exactly what it should, and the output look fine, with the unification, but, when I try to insert the items into the Enrichment Chamber the shift-click does nothing and if I put manually inside it just doesn't work (Doesn't crush)... I never see issue like that without Unidict...

I try to add manually the recipes for the dust with Crafttweaker but, look like unidict remove all recipe after Crafttweaker does is change, so, this is just impossible for me to fix that issue manually...

Is it not possible for unidict to not break all the change a modpack dev make with crafttweaker?? This look really really bad thing, when a mod does everithing automatically, without soo mutch control overpass every other change possible...

I hope you can do something about that, and possibly change the order of execution, question to still have little-bit of control. PS: If it stay the same in the future, I can garantee you, I will never use Unidict anymore in any of my new modpack (So bad, because it can be helpfull, question to unify thing fast...)

**Comment by WanionCane** [comment]
it is indeed broken, for now, turn it off, I will take a better look on it on a few days.

**Comment by Fireztonez** [comment]
ok perfect...
I have turned off that feature and fix all unification myself with crafttweaker...

Thank's
Fireztonez

**Comment by LumberWizard** [comment]
I wanna add that after unifying sawdust, the Mekanism precision sawmill still makes Mekanism sawdust instead of Thermal Foundation sawdust.

**Comment by katur239** [comment]
> it is indeed broken, for now, turn it off, I will take a better look on it on a few days.


@Fireztonez This is a bit old but I'm having the same issue it still isn't fixed from what I can see. Do you by chance still have your crafttweaker fixes and can share them? Thanks!

**Comment by Wxrlds** [comment]
Any updates on this one?

**Comment by aaronhowser1** [comment]
This is still an issue

**Comment by ElektroKill** [comment]
This issue should no longer be a problem in the latest unidict (2.9.9)
