### ISSUE TITLE
Possible Rendering Issues

### ISSUE THREAD

**Issue by JathTyki** [WanionCane/UniDict#13]
Hello,

I think there are some rendering issues with UniDict in the newest version (2.5b). If you hover over an ingot to get the tooltip, it will crash the game completely. If I remove UniDict, it no longer crashes (that I've noticed so far, so if it's something else causing the issue, I don't know).

http://pastebin.com/bRSXZBjC

**Comment by WanionCane** [comment]
after reading your crash report, seems that is somehow fault of MineTweaker.
try removing it, or, if there is some script adding additional tooltips, disable the scripts.
if is indeed an incompatibility between UniDict and MineTweaker/CraftTweaker, I have no clue about why this is happening =/
thanks for the report =P

**Comment by WanionCane** [comment]
If you have some news about this issue, feel free to re-open.
