### ISSUE TITLE
Railcraft not getting unified

### ISSUE THREAD

**Issue by Staegrin** [WanionCane/UniDict#130]
Sadly it seems to be random if it unifies or not for Railcraft ingots/nuggets. When I turn 9 thermal expansion ingots into blocks and turn the block back into ingots I get the Railcraft variants. copper/tin/lead/silver/nickel/zinc/steel

Maby because railcraft isn't included in integrationModule.cfg

Railcraft was the last mod updated/added to the pack so it's materials take precedence?

random unifying happens for instance when I put the railcraft variants of the ingots into the manual rolling machine and leave the gui (-> you have to keep looking into the gui to make the machine work) then the thermal variants get spit out.

edit:This random unifying no longer happens after another few updates to various mods.

issue #128 started this but was closed again probably because of the randomness.

**Comment by skarr71** [comment]
Issue still not solved. any help would be appreciated

**Comment by Staegrin** [comment]
Best solution so far is to use crafttweaker to remove the recipes.

**Comment by ProxyPlayerHD** [comment]
still not solved it seems.

I set gregtech to have the highest priority... but still:

Gregtech Ingots -> Railcraft Nuggets
Gregtech Nuggets -> Railcraft Ingots

the way i'll use to fix this is by disabling all metal ingots/nuggets/blocks from railcraft so it's forced to use some other mod's

**Comment by Staegrin** [comment]
`//removes charcoal block recipe from other mods
recipes.remove(<actuallyadditions:block_misc:5>);
recipes.remove(<mekanism:basicblock:3>);
recipes.remove(<forestry:charcoal:0>);`

`//removes Railcraft ingots and nuggets recipes
recipes.remove(<railcraft:ingot:0>);
recipes.remove(<railcraft:ingot:1>);
recipes.remove(<railcraft:ingot:2>);
recipes.remove(<railcraft:ingot:3>);
recipes.remove(<railcraft:ingot:4>);
recipes.remove(<railcraft:ingot:5>);
recipes.remove(<railcraft:ingot:6>);
recipes.remove(<railcraft:ingot:7>);
recipes.remove(<railcraft:ingot:8>);
recipes.remove(<railcraft:metal:0>);
recipes.remove(<railcraft:metal:1>);
recipes.remove(<railcraft:metal:2>);
recipes.remove(<railcraft:metal:3>);
recipes.remove(<railcraft:metal:4>);
recipes.remove(<railcraft:metal:5>);
recipes.remove(<railcraft:metal:6>);
recipes.remove(<railcraft:metal:7>);
recipes.remove(<railcraft:metal:8>);
recipes.remove(<railcraft:nugget:0>);
recipes.remove(<railcraft:nugget:1>);
recipes.remove(<railcraft:nugget:2>);
recipes.remove(<railcraft:nugget:3>);
recipes.remove(<railcraft:nugget:4>);
recipes.remove(<railcraft:nugget:5>);
recipes.remove(<railcraft:nugget:6>);
recipes.remove(<railcraft:nugget:7>);
recipes.remove(<railcraft:nugget:8>);`

`//removes mekanism storage blocks that don't get unified
recipes.remove(<mekanism:basicblock:1>);
recipes.remove(<mekanism:basicblock:5>);
recipes.remove(<mekanism:basicblock:12>);
recipes.remove(<mekanism:basicblock:13>);`

**Comment by ProxyPlayerHD** [comment]
i mean that also works, but wouldn't that require you to also install CraftTweaker?

also in an unrelated note, anyone know if UniDict screws with furnace recipes? becuase i made a gregtech pack with it and for some reason i can smelt Aluminium, Tungsten, and other high end metals in a simple furnace... which should not be possible and breaks all progression

**Comment by Staegrin** [comment]
Yes to both. Though craftTweaker is extremely useful in both adding and removing recipes. I love using it to add recipes to process ores and resources when they would otherwise need to be broken in world -> lag or just don't have a way to be processed.

As to the smelting. If another mod adds a smelting recipe and it gets Unified, the dust will be smeltable. Thermal mod aluminium is smeltable in regular furnace -> gregtech aluminium will go in the furnace. Though I would recommend checking the configs.

**Comment by H0bbitBaron** [comment]
Same for Villager trades, requiers ingots from Railcraft, though i set UniDict for Thermal* and fixed some recipies with CraftTweaker:

![image](https://user-images.githubusercontent.com/36517776/71554066-64b89480-2a2b-11ea-806b-2724c8d083f5.png)

**Comment by MrLador** [comment]
I was looking for ways to fix it myself. I just disabled Item ingots and railcraft dusts via item config.

**Comment by ElektroKill** [comment]
Fixed in UniDict 3.0.3
