### ISSUE TITLE
Crafting ingots to blocks is using Mekanism not Thermal Foundation

### ISSUE THREAD

**Issue by JakeMoe** [WanionCane/UniDict#132]
I think this is the same issue as #62 but would like to clarify that even though UniDict has support for Mekanism, their recipes can override the Thermal ones I'm trying to get using this mod?  If so, then is my solution to use CraftTweaker to make ingots turn into a TF block rather than a Mekanism block?

**Comment by xJon** [comment]
I can also confirm this issue.
![Screenshot_3](https://user-images.githubusercontent.com/8945347/63214252-4f685b00-c159-11e9-8aff-21e43b687b18.png)

**Comment by ElektroKill** [comment]
Fixed it in my fork https://github.com/ElektroKill/UniDict. Will do a PR once I collect more changes!
