### ISSUE TITLE
Broken Recipe For Nuggets To Ingots/Ingots To Blocks

### ISSUE THREAD

**Issue by RemovePlays** [WanionCane/UniDict#133]
UniDict 1.12.2-2.9.2 on Forge 14.23.5.2815
The recipes for converting metal nuggets & ingots (added from Thermal Foundation) into ingots & blocks are not working. The recipes are listed correctly in NEI, though they do not seem to work in any crafting table. The items can be placed in the table, but no there is no output. The tooltip says the recipe is added by UniDict. I don't believe any mods added are interfering with the recipe.

**Comment by BonaireDreams** [comment]
I'm having the same issue with Railcraft-12.0.0 and UniDict 1.12.2-2.9.2  Thermal Expansion blocks/ingots are the preferred.  Converting a TE block of Copper, Tin, Invar, Lead, Silver, Steel, Nickel always gives the Railcraft Ingots. Unless the recipe option for "no more recipe conflict" mod is clicked to the next recipe.

![image](https://user-images.githubusercontent.com/5133282/56464132-8ee38e00-6397-11e9-85ac-fd637410b47e.png)

After clicking the "2->" icon
![image](https://user-images.githubusercontent.com/5133282/56464133-a15dc780-6397-11e9-9a90-351905f6f354.png)

I've even tried removing the railcraft Block to ingot recipes via.
recipes.removeShapeless(<railcraft:ingot:1> *9, [<ore:BlockCopper>]);
This also did not work.

Any chance we can get Railcraft added to Unidict integration so we can set its priority lower than Thermal Expansion?

**Comment by H0bbitBaron** [comment]
Same with Villager trades: https://github.com/WanionCane/UniDict/issues/130
@BonaireDreams if it still matters, I fixed some issues like this:
`
recipes.remove(<railcraft:nugget:2>, true);
recipes.remove(<railcraft:ingot:2>, true);
recipes.remove(<railcraft:metal:2>, true);
recipes.remove(<railcraft:gear:2>, true);
`

**Comment by ElektroKill** [comment]
Fixed in UniDict 3.0.3
