### ISSUE TITLE
[1.12.2] crafttweaker <ore:~>.firstItem output wrong

### ISSUE THREAD

**Issue by Spodi** [WanionCane/UniDict#135]
Long story short: crafttweaker doesn't output the sorted item in a recipe.
E.g.: <ore:ingotZinc>.firstItem should result in a metallurgy ingot (ownerofeverything), but it is from a different mod (moreplanets) instead.
This worked fine in 1.7.10, but i think CT or unidict changed something

**Comment by WanionCane** [comment]
CraftTweaker create their recipes before UniDict unification occurs, so, this is expected to happen.
