### ISSUE TITLE
IC2 compatibility with new coke oven

### ISSUE THREAD

**Issue by LumberWizard** [WanionCane/UniDict#138]
Very recently IC2 added a coke oven multiblock (it's in their public CruseForge betas). Coal coke produced by it is not unified, even though it is in fuelCoke and I have fuelCoke set to unify.

**Comment by WanionCane** [comment]
sorry for the huge delay, I am no longer working on UniDict for 1.12.2.

**Comment by gatoborrachon** [comment]
mmm, maybe we can retake this issue since UniDict came back?
