### ISSUE TITLE
Immersive Engineering plates can still be crafted

### ISSUE THREAD

**Issue by Dimentive** [WanionCane/UniDict#139]
I’m playing a custom modpack, and Immersive Engineering plates (iron, gold, and steel) can still be crafted despite the fact that UniDict is supposed to unify them. They don’t appear in JEI, which is good, but unfortunately, in my game, they’re still fully craftable using the forge hammer.

Similar to #90.

#### Versions
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2816
* **WanionLib:** [2.2](https://minecraft.curseforge.com/projects/wanionlib/files/2651482) (latest)
* **UniDict:** [2.9.2](https://minecraft.curseforge.com/projects/unidict/files/2652588) (latest)
* **Immersive Engineering:** [0.12 - 89](https://minecraft.curseforge.com/projects/immersive-engineering/files/2676501) (latest)

**Comment by WanionCane** [comment]
sorry for the huge delay, I am no longer working on UniDict for 1.12.2.
