### ISSUE TITLE
[Suggestion] Loot table integration

### ISSUE THREAD

**Issue by katur239** [WanionCane/UniDict#14]
So I ran into an issue with Immersive engineering where it was putting it;s own version of ingots in it's villager house crates from a loot table.

I've been researching how I can fix that and it looks like loottweaker may be what I use. But this got me thinking how nice it'll be if this was part of the automatic stuff unidict does since it kind of fits into it's scope.

I have no idea how hard it'll be to do but I thought I would suggest it anyways. Thanks!

**Comment by WanionCane** [comment]
UniDict for 1.71.0 have "Chest" Integration, I think it is exactly what you are saying.
but, I tried to port it to 1.9.4+ and, a lot of things changed on vanilla, so I am not sure yet how could I implement it.
but thanks, I will add this to my todo list =P
