### ISSUE TITLE
Primalcore / Unidict compatibility issue

### ISSUE THREAD

**Issue by estradus** [WanionCane/UniDict#140]
Primalcore adds a recipe to make horse armor using Iron Plates, and also adds a recipe to salvage horse armor into plates using a tool added called the Work Knife.  The work knife looses durability as you use it to craft stuff.  Because the recipe makes plates, it was taken over by Unidict.  

The Unidict version of the recipe only works if the tool is at 100% durability, otherwise it is not considered the correct item.  

Is it possible to make some official integration or adjustment for tool consumption?

**Comment by WanionCane** [comment]
sorry for the huge delay, I am no longer working on UniDict for 1.12.2.
