### ISSUE TITLE
Immersive Engineering Villagers

### ISSUE THREAD

**Issue by CritFlaw** [WanionCane/UniDict#141]
The immersive engineering structural engineer uses copper + emeralds to trade for deposit maps. This remains as IE copper, while everything else is changed to, in my case, thermal expansion copper. IE dev says this should be handled by UniDict since villagers can't handle oredict, so it has to be a specified ingot.

**Comment by WanionCane** [comment]
in this case, I would suggest you to make the IE bars/dusts/so on... to be the default =P

**Comment by ElektroKill** [comment]
Sadly it is not possible to fix the deposit map trades, I have however fixed the other immersive trades.
