### ISSUE TITLE
Dust AE2 and ic2 macerator [Question]

### ISSUE THREAD

**Issue by AbrahamArmasCordero** [WanionCane/UniDict#142]
Problem:
Macerator of ic2 doesnt  make any dust of AE2 after install of this mod.

Right now AE2 does not support Macerator recipes of IC2 so you can not automatize the dust making in AE2 Shouldn't this mod Add it?

I read in [this Post](https://forum.industrial-craft.net/thread/15506-can-t-grind-ae2-certus-quartz/) that AE2 wants IC2 to implement the recipes. Since this is a unification mod and right now the recipes are not supported Can i ask you to add them? :D Maybe not i dont know how this works i tried to read the wiki but im baby programmer so i dont get any of those things

**Comment by WanionCane** [comment]
well UniDict AE2 Integration doesn't create recipes, it just changes the outputs of them.
but yeah, it could be done, but, I am no longer working on UniDict for 1.12.2.
