### ISSUE TITLE
Iron plates

### ISSUE THREAD

**Issue by kirillpukhov2004** [WanionCane/UniDict#143]
How to change the recipe for crafting iron plates with a hammer from Immersive Eng. (UniDict added) to craft with a hammer from IC2?
Versions
Minecraft: 1.12.2
Forge: 14.23.5.2838 (latest)
WanionLib: 2.2 (latest)
UniDict: 2.9.2 (latest)
Immersive Engineering: 0.12 - 89 (latest)

**Comment by WanionCane** [comment]
you can change them with craft tweaker, but don't forget to remove the original recipe, and, it doesn't matter the output that you gave to the recipe, UniDict will standardize it later.
