### ISSUE TITLE
Placebo breaks shapeless crafting table recipe unification.

### ISSUE THREAD

**Issue by LumberWizard** [WanionCane/UniDict#148]
Testing environment: JEI, IC2, Thermal Foundation, UniDict.
Without placebo, petrotheum/pyrotheum dust crafting table recipes are handled as expected, outputting Thermal Foundation dusts or ingots.
With placebo, they output IC2 dusts and ingots, despite thermal foundation having a higher priority in UniDict.

**Comment by WanionCane** [comment]
sorry, I am no longer working on UniDict for 1.12.2.

**Comment by ElektroKill** [comment]
I’ve recently faced this problem too, might look into fixing it. :)

This is probably caused by Placebo replacing the vanilla ShapelessRecipes with instances of it’s own FastShapelessRecipe.

**Comment by ElektroKill** [comment]
Fixed it in my fork (https://github.com/ElektroKill/UniDict).

I will open a PR once I compile a bit more fixes and improvements for the 3.0.0 version!
