### ISSUE TITLE
Ae2 grindstone

### ISSUE THREAD

**Issue by katur239** [WanionCane/UniDict#15]
Version 2.5c doesn't seem to be working with the grindstone in ae2 rv4-11. It is giving me the advanced rocketry version of copper instead of what it's supposed to (unified items).

Ae2 isn't an option in the integration cfg either.

**Comment by katur239** [comment]
Oh, I should of looked at changelogs.. Nevermind.

**Comment by WanionCane** [comment]
lol XD
as soon as possible I will re-enable it, don't worry. =P

**Comment by katur239** [comment]
To be fair, I looked at the curse page and it still has AE2 listed as implemented. XD

But no worries! Thanks
