### ISSUE TITLE
Immersive Engineering hammer issues

### ISSUE THREAD

**Issue by Shandoo94** [WanionCane/UniDict#150]
The recipes to craft plates with the immersive enigeering hammer in the crafting grid doesn't get unified. They result in IE plates instead of Thermal Foundation plates.

Forge 14.23.5.2838
Immersive Engineering 0.12-92
UniDict 2.9.3

**Comment by ElektroKill** [comment]
I am unable to reproduce this issue with the latest versions of the mentioned mods.
