### ISSUE TITLE
Actually Additions double crushers don't get unified, they output AA curshed coal, while other pulverizers from other mods output Thermal Foundation/Expansion pulverized coal.

### ISSUE THREAD

**Issue by Gliese-832-c** [WanionCane/UniDict#153]
![grafik](https://user-images.githubusercontent.com/55159077/69914172-49b12f80-1441-11ea-8b0c-e96363164e9f.png)
![grafik](https://user-images.githubusercontent.com/55159077/69914176-55045b00-1441-11ea-934a-54901e195884.png)
![grafik](https://user-images.githubusercontent.com/55159077/69914190-7ebd8200-1441-11ea-9e2f-b53d84197021.png)

**Comment by ElektroKill** [comment]
Resolved this in my PR, should be fixed in the 3.0.0 release.
