### ISSUE TITLE
UniDict breaks forestry carpenter recipes

### ISSUE THREAD

**Issue by calvss** [WanionCane/UniDict#156]
I'm on forge 2847, forestry 5.8.2.387 and UniDict 2.9.5

Normally, you should be able to put a broken pickaxe/shovel into a carpenter and get the bronze ingot back. However if you add unidict it just says "no recipe"

![image](https://user-images.githubusercontent.com/13447929/72973462-44041480-3e08-11ea-91b2-54432d31ff7e.png)

**Comment by ElektroKill** [comment]
Fixed in my work in progress PR :)
