### ISSUE TITLE
Possible Additional Pipes bug?

### ISSUE THREAD

**Issue by AveoCross** [WanionCane/UniDict#16]
Hi! I just created Issue on Additional Pipes github about missing Advanced Wooden Pipe missing recipe. I suspect that UniDict has something to it maybe. 
I'm using UniDict 2.9.2 for MC 1.7.10. 
More [HERE](https://github.com/tcooc/AdditionalPipesBC/issues/152).

**Comment by WanionCane** [comment]
I am not sure how UniDict would interfere with Additional Pipes, unless their items are being registered on ore dictionary as being something that UniDict is trying to unify.

**Comment by AveoCross** [comment]
In AP release 4.7.5:
"Make all recipes use the Forge Ore Dictionary. Among other things, this will allow you to use glass from other mods to make Additional Pipes's pipes."
Maybe something with this?

**Comment by WanionCane** [comment]
I mean, the recipe output, not the inputs.

**Comment by AveoCross** [comment]
I know but I thinking maybe it's related or something. 
But I just checked and tried without UniDict and issue still exist so it's not UniDict fault. So sorry for taking time ^^"

**Comment by WanionCane** [comment]
no problem =P
