### ISSUE TITLE
Techreborn grinder not unifying.

### ISSUE THREAD

**Issue by Saxymansam** [WanionCane/UniDict#161]
So I do not know if it is tech reborn thing or Unidict thing

UniDict-1.12.2-2.9.5.jar
ThermalFoundation-1.12.2-2.6.3.27-universal.jar
TechReborn-1.12.2-2.26.3.1066-universal.jar

But if you use the grinder it spits out the Techreborn dusts and not the Thermal foundation.

Plus other things in Techreborn seems not to unify, but the grinder is the first one I have seen.

**Comment by furtabs** [comment]
its unidicts fault TR broke something
