### ISSUE TITLE
Please add support for Mekanism

### ISSUE THREAD

**Issue by ElektroKill** [WanionCane/UniDict#162]
Hi,
I know Mekanism support was removed due to some changes in their code but is it possible to bring it back? My reason for is that when I smelt Mekanism ores in the energized smelter I get Mekanism ingots but when I smelt TE ore I get TE ingot. However when using a furnace both result in a TE ingot. Is there a possibility for this to be fixed ?

I am using Mekanism 1.12 version.

Thanks in advance.

**Comment by ElektroKill** [comment]
I tested out the older 2.9.2 version of UniDict which has the old removed Mekanism Integration and I can say that it works on the latest mekanism version.

**Comment by fabm3n** [comment]
Not working for me with 2.9.2 UniDict and 1.12.2-9.8.3.390 Mekanism

**Comment by Endoman123** [comment]
I agree with bringing back the Mekanism integration; at the very least, have it as an "experimental" opt-in feature since some versions of Mekanism don't work with Unidict apparently.

I will add, though, that the Mekanism integration is working on UniDict 1.12.2-2.9.2 and Mekanism 1.12.2-9.8.3.390

**Comment by busti** [comment]
Can confirm; Mekanism integration works with
- Mekanism 1.12.2-9.8.3.390
- UniDict 1.12.2-2.9.2
- WanionLib 1.12.2-2.2  

It would be nice to have proper support for this though, especially since mekanism seems to be stable and is unlikely to receive any more updates for 1.12.

**Comment by ElektroKill** [comment]
I've added a fixed version of the Mekanism integration in this PR(#175). Let's hope the project author merges it.
