### ISSUE TITLE
Blocks of Charcoal

### ISSUE THREAD

**Issue by xJon** [WanionCane/UniDict#169]
Is there any chance this mod could also unify blocks of charcoal?
It'd prove useful as many mods add their own version, and automating the removal of excess versions is great for modpacks.

**Comment by WanionCane** [comment]
it is possible, check UniDict.cfg

**Comment by xJon** [comment]
@WanionCane Would it be added here?
```
    # Here you can put a list to custom unify them.
    # must be in this format "ResourceName:kind1|kind2|...". [default: [Obsidian:dustTiny|dust], [Stone:dust], [Obsidian:dust|dustSmall], [Coal:dust|dustSmall], [Sulfur:dust|dustSmall], [Salt:dust]]
    S:customUnifiedResources <
        Obsidian:dustTiny|dust
        Stone:dust
        Obsidian:dust|dustSmall
        Coal:dust|dustSmall
        Sulfur:dust|dustSmall
     >
```
I'm sorry but I can't tell for sure where to add it.

**Comment by WanionCane** [comment]
it should look like this:

> Coal:dust|dustSmall|block

**Comment by xJon** [comment]
Thank you :)
