### ISSUE TITLE
IC2 Forge Hammer not functional

### ISSUE THREAD

**Issue by ghost** [WanionCane/UniDict#17]
Hi there,

we're running a server with 1.7.10 and we're using industrialcraft-2-2.2.823-experimental. We just installed UniDict 2.9.1 on the server and have B:keepOneEntry set to true. Now we have the problem that the IC2 Forge hammer isn't functional anymore. Well, it stil can be used to make item casings, but not the plates. And this a very critical part, because the machines which can be used to make item casings... well they need item casings. So there is no substitue for that. I've seen that there is a fix in versions > 1.7.10 - but upgrading isn't an option for us. Could you do a hotfix for that? Or do you have a workaround?

**Comment by WanionCane** [comment]
hello.
I took a look, and seems to be working fine.
could you check the usages of Forge Hammer to see if there is no recipe using it?
thank you.

**Comment by ghost** [comment]
There are just two recipes for the iron plates, one by the block cutting machine and the other one by the metal former. No recipe for the hammer. The only recipes with the hammer are the casings.

**Comment by ghost** [comment]
![grafik](https://cloud.githubusercontent.com/assets/5868414/22862839/b2480b4e-f136-11e6-8f5d-295c088273ba.png)

**Comment by ghost** [comment]
![grafik](https://cloud.githubusercontent.com/assets/5868414/22862840/bf6adb3a-f136-11e6-9fc1-ec7c2d325634.png)
![grafik](https://cloud.githubusercontent.com/assets/5868414/22862842/c51b9fec-f136-11e6-85be-ea4ad081cfb0.png)

**Comment by ghost** [comment]
![grafik](https://cloud.githubusercontent.com/assets/5868414/22862844/d8ccebd6-f136-11e6-873e-5ef03c9682ee.png)

**Comment by WanionCane** [comment]
oh, I just noticed that you aren't using the latest version for 1.7.10. try with [this](https://minecraft.curseforge.com/projects/unidict/files/2329986), tell me if with it works. =P

**Comment by ghost** [comment]
Oh damn, my mistake sorry. I did think I had the last version. This fixed the issue, thanks for your fast reply!

**Comment by WanionCane** [comment]
no problem XD
