### ISSUE TITLE
Add ability to use regex in recipeToRemoveList 

### ISSUE THREAD

**Issue by Endoman123** [WanionCane/UniDict#170]
As the title says, would allow to easily remove groups of recipes using the same pattern.

E.g: removing all the shaped gear recipes requires that you type `"unidict:gearthorium_x4_shape. a aba a "` which takes a long time and is prone to error if you are unifying 20+ materials, in comparison to simply `unidict:gear.*_x\d+_shape\..*` to match all shaped gear recipes.

**Comment by WanionCane** [comment]
this is a great idea =D
