### ISSUE TITLE
One Ingot = Gear in IE Metal Press

### ISSUE THREAD

**Issue by Partonetrain** [WanionCane/UniDict#18]
When Immersive Engineering integration is enabled, the ingot to gear ratio is 1:1. I can't imagine this is intentional as 4 ingots have otherwise always equaled one gear.

**Comment by WanionCane** [comment]
could you try with this? [UniDict-1.10.2-2.6b.jar](https://minecraft.curseforge.com/projects/unidict/files/2384001)
thanks.

**Comment by Partonetrain** [comment]
You fixed it, thank you.
