### ISSUE TITLE
Unified Recipes Are Broken

### ISSUE THREAD

**Issue by SaltSouls** [WanionCane/UniDict#187]
I know that title doesn't give much information, but I will. Right now it seems that no matter what I do, be that change the order of the unity, to trying to change/remove the recipes from the game using CT, all ingots/nuggets/blocks are unifying to the wrong variant. An example would be that UniDict should be unifying all ingots/nuggets/blocks to IE(Immersive Engineering), and while it does this when smelting the ores, the instant you try to craft the block/nuggets/ingots, the item changes mod. In terms of copper it will go from IE to RC(RailCraft). I have tried using CT to fix this, but even that doesn't seem to be  able to fix the problem. I'm not sure if this is due to some kind of mod incompatibility with UniDict, but it is annoying none the less when trying to unify all of the metals as best as one can.
No changes were made to the config besides the order of S:ownerOfEveryThing.
`~CONFIG_VERSION: 1.12.2-3.0.2`
`S:ownerOfEveryThing <
        minecraft
        immersiveengineering
        mystgears
        mysticalmechanics
        immersiveintelligence
        embers
        railcraft
     >`

**Comment by SaltSouls** [comment]
Okay, so I did figure out what the problem was in regards to CT not being able to edit recipes. Though the issue with the unification without it remains the same.

**Comment by ElektroKill** [comment]
The problem is that UniDict doesn’t support railcraft due to the way they handle recipes. I will look into a padding support but I can’t promise anything.

**Comment by SaltSouls** [comment]
That would be much appreciated and I understand if nothing can be done. I'm interested in how RC does their recipes considering I thought there was really only one way of going about them.

**Comment by ElektroKill** [comment]
I’ve managed to get a working crafting integration (only for the crafting table for now), the problem with railcraft is that it registers a lot of custom recipe classes and ingredient types which need to be handled. However I came to the conclusion that the recipes that need to be unified don’t use those ingredients making it much simpler.
I am currently working on adding support for the metal rolling and blast furnace of railcraft.

**Comment by SaltSouls** [comment]
I greatly appreciate the fast responses! Not to rush you or anything, but is there a timeframe in which these implementations can be expected to be released?

**Comment by ElektroKill** [comment]
Hello, I should be able to release the changes before Christmas. I will do some other improvements and then push the 3.0.3 update out

**Comment by ElektroKill** [comment]
I've released the UniDict 3.0.3 update which brings support for RailCraft crafting recipes, villagers, and machines(Blast Furnace, Metal Rolling, Rock Crusher).

**Comment by SaltSouls** [comment]
> I've released the UniDict 3.0.3 update which brings support for RailCraft crafting recipes, villagers, and machines(Blast Furnace, Metal Rolling, Rock Crusher).

Massive thanks for being so quick about it!
