### ISSUE TITLE
Crash on Load Ver.3.0.3-dev

### ISSUE THREAD

**Issue by SaltSouls** [WanionCane/UniDict#188]
The new version seems to crash the game upon starting it up.
Not sure if this is Unidict that is causing a crash or some kind of mod incompatibility.
[Log file](https://hastebin.com/awaguhigon.rb)

**Comment by ElektroKill** [comment]
The versions ending with -dev are meant to be used in the development environment, where the game is fully deobfuscated. In a normal runtime environment, the names are obfuscated. Use the version without the -dev suffix.

**Comment by SaltSouls** [comment]
> The versions ending with -dev are meant to be used in the development environment, where the game is fully deobfuscated. In a normal runtime environment, the names are obfuscated. Use the version with the -dev suffix.

Oops, sorry. That's all on me being dumb... Guess I downloaded the wrong one somehow.

**Comment by ElektroKill** [comment]
I assume this is fixed now, closing the issue!
