### ISSUE TITLE
[Feature Request] Integration for Chickens and Hatchery

### ISSUE THREAD

**Issue by JackyyTV** [WanionCane/UniDict#19]
I have Thermal Foundation metals set as default in UniDict for my 1.10.2 pack, most of the stuff are overrided except for the chicken drops (Copper Chicken, Steel Chicken, etc.) in the Chickens mod and Hatchery. Apparently libVulpes didn't get overrided by UniDict in that two mods mentioned, which I found quite annoying as I wanted to keep all the metals from 1 mod, just like below:
Current situation:
![Before overrided](https://i.gyazo.com/e992200b7a2618d016c40d8a83e96057.png)

Desired situation:
![After overrided](https://i.gyazo.com/f0e875b7ebd3344d2b01cc4bab293b88.png)
Is it possible to have UniDict integrates with Chickens and Hatchery so it completely overrides the oredict entries with the desired ones? Thank you.

**Comment by WanionCane** [comment]
I will take a look, thank you =P

**Comment by JackyyTV** [comment]
You're welcome :)

**Comment by WanionCane** [comment]
done =P [UniDict-1.10.2-2.8](https://minecraft.curseforge.com/projects/unidict/files/2396130)

**Comment by JackyyTV** [comment]
Thank you! :D
