### ISSUE TITLE
keepOneEntryKindBlackList not working

### ISSUE THREAD

**Issue by H-QueerCoded** [WanionCane/UniDict#194]
**Describe the bug**
With `keepOneEntry=true`, kinds in the keepOneEntryKindBlackList are still having items removed from the oredict.

**To Reproduce**
1. enable keepOneEntry
2. add a kind (i used block and gear) to keepOneEntryKindBlackList
3. launch game
4. use something like `/ct hand` to see that items are still being removed from oredicts

**Expected behavior**
Items of the blacklisted kind won't be removed from their oredict and can be used in oredict recipes

**Additional context**
In particular I was trying to blacklist blocks so that Chisel functionality wouldn't be affected for metal blocks.
Here's the config file with the extension changed so github will let me upload it
[UniDict.cfg.txt](https://github.com/WanionCane/UniDict/files/5961162/UniDict.cfg.txt)

**Comment by ElektroKill** [comment]
Hello, I did some changes to the blacklist already because I noticed a problem with it too. Could you check if this issue still persists with the build mentioned in this issue comment?
https://github.com/WanionCane/UniDict/issues/192#issuecomment-775933267

**Comment by H-QueerCoded** [comment]
Issue is fixed in that build, thanks!
