### ISSUE TITLE
Astral Sorcery module makes Astral Sorcery grindstone not work

### ISSUE THREAD

**Issue by TCreopargh** [WanionCane/UniDict#198]
**Describe the bug**
When right clicking on a grindstone with a rock crystal, nothing happens.
By editing config\unidict\IntegrationModule.cfg and change B:AstralSorcery=true to false, this problem is resolved, so it's a problem of this mod.

**To Reproduce**
1. Install this mod & astral sorcery then Craft grindstone
2. Get rock crystal
3. Right click on grindstone with rock crystal
4. Crystal doesn't get inserted

**Expected behavior**
The crystal should go into the grindstone so you can improve its stats.

**Screenshots**

**Additional context**
Original issue of my modpack: https://github.com/TCreopargh/GreedyCraft/issues/169

**Comment by ElektroKill** [comment]
Fixed the issue! Please wait patiently for release 3.0.8
