### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by BloodWorkXGaming** [WanionCane/UniDict#20]
Hey ^^
Something like reload command would be really helpfull.
Since we have a modpack with about 200 mods in it, it takes 3-4 mins to start that pack.
Doing that on every change is a bit annoying, is it possible to add that in general or not, since i am not sure whether the ingots get hindered from being inited.

**Comment by WanionCane** [comment]
sorry for the delay, well, this is indeed possible, but it wouldn't work for indirect integrations =/
thanks for your suggestion =P

**Comment by WanionCane** [comment]
sorry for the huge delay, lol
for now, I ain't going to implement this, at least not now
