### ISSUE TITLE
[Suggestion] More documentation for configs

### ISSUE THREAD

**Issue by Xavienth** [WanionCane/UniDict#200]
**Describe your feature suggestion in detail**
The wiki only covers basic information on how to use the configs, and then information for mod developers. It is not clear how to, for example, use the specific entry sorting function.

**Is your feature request connected with any other mods? If yes, please list them**
No.

**Additional information**
I'm trying to have one specific kind have a different owner than the default order, and I cannot for the life of me find any documentation on the formatting of specificEntrySorting.json.

**Comment by Xavienth** [comment]
I'm blind and didn't see the formatting guide file lmao. Closing.

**Comment by ninjakitty7** [comment]
Sorry to comment on an old issue but I've been banging my head against the wall trying to find literally any documentation on the configs. All I need to do is blacklist a single item from being unified and hidden so that it exists normally. Where did you find documentation?

**Comment by Xavienth** [comment]
> 

You should have a file named jsonFormatGuide.txt in .minecraft\config\unidict.
Here it is just in case
[jsonFormatGuide.txt](https://github.com/WanionCane/UniDict/files/8282655/jsonFormatGuide.txt)
