### ISSUE TITLE
BaseMetal Integration for new versions

### ISSUE THREAD

**Issue by BakermanLP** [WanionCane/UniDict#21]
Hello,

the mods around basemetals get a update at the Moment. But there are some changed functions, that should be adressed in Unidict:

https://github.com/WanionCane/UniDict/blob/1.10.2/src/main/java/wanion/unidict/integration/BaseMetalsIntegration.java

Here is a pastebin of the error:
http://pastebin.com/raw/Jd1vFahg

Used versions:
* BaseGems-1.10.2-2.5.0-beta1.11.jar
* BaseMetals-1.10.2-2.5.0-beta1.58.jar  
* BaseMinerals-1.10.2-2.5.0-beta1.10.jar  
* UniDict-1.10.2-2.7.jar  
* WanionLib-1.10.2-1.3.jar

Can you fix that? 

Thanks in advance

Michael (aka BakermanLP)

**Comment by WanionCane** [comment]
thanks, this will be fixed asap.

**Comment by WanionCane** [comment]
sorry for the huge delay².

so, I couldn't find any issues.
I am using this version: BaseMetals_1.10.2-2.4.0.11

I couldn't find the version BaseMinerals-1.10.2-2.5.0-beta1.10 that you are using.

thanks.
