### ISSUE TITLE
[Suggestion] Integration of Better with mods

### ISSUE THREAD

**Issue by BakermanLP** [WanionCane/UniDict#22]
Hello there,

first of all I wanted to say, that I love your mod. It saves me much time to get a modpack together.

In this situation I ran into some difficulties. I wanted to integrate the mod "Better with mods" into my upcoming modpack. But this little thing has it's own nuggets. 

Can you have a look at this and make it the "UniDict" way?

Here are some URLs, that might be helpfull:
https://minecraft.curseforge.com/projects/better-with-mods
https://github.com/BeetoGuy/BetterWithMods

Thank you for reading

Michael (aka BakermanLP)

**Comment by WanionCane** [comment]
I will take a look, thank you =P

**Comment by WanionCane** [comment]
sorry for the huge delay.

I took a look, but  I couldn't find any recipe that needs their output standardized.
if possible, could you say which machine/recipe I need to take a look at?
thank you.
