### ISSUE TITLE
Crash on 1.11.2 version

### ISSUE THREAD

**Issue by POKFX45** [WanionCane/UniDict#23]
The game could not load, i got this crash, it starts at line 1229

https://paste.ee/p/LTOnu

**Comment by WanionCane** [comment]
thanks, I will take a look.

**Comment by WanionCane** [comment]
hey, seems that you're using the dev version.. =O

**Comment by WanionCane** [comment]
I tried here, and works perfectly, you should download the non-dev jar.
[UniDict-1.11.2-1.0.jar](https://minecraft.curseforge.com/projects/unidict/files/2411371)

**Comment by POKFX45** [comment]
Thanks! Sorry for the inconvenience!
