### ISSUE TITLE
[1.10.2] Not supporting TechReborn fusion reactor

### ISSUE THREAD

**Issue by Skillotic0703** [WanionCane/UniDict#24]
The fusion reactor yields platinum dust and iridium ore from TR and not from Thermal foundation.

**Comment by WanionCane** [comment]
it should work for all machines, I will take a look, thank you.

**Comment by WanionCane** [comment]
sorry for the huge delay
so, I added support for it in the 1.12.2 version of UniDict, are you still playing 1.10.2?
if yes, then I will include support for fusion reactor on the next 1.10.2 update.

**Comment by WanionCane** [comment]
Implemented on [UniDict-1.12.2-1.6](https://minecraft.curseforge.com/projects/unidict/files/2508665)
