### ISSUE TITLE
Classic ic2 causes crash.

### ISSUE THREAD

**Issue by grydian** [WanionCane/UniDict#25]
I tried disabling the ic2 integration and removing it from the list of possible outputs.  It still crashed.  Here is the crash log.

https://pastebin.com/Ty3ujm86

**Comment by WanionCane** [comment]
oh, thanks for reporting this, I will take a look asap =P

**Comment by Speiger** [comment]
IC2C has its own RecipeAPI where you can read all the items from.
I told you that long ago but i forgot to tell you the release. Thats my fault in this case. ^^"

https://github.com/TinyModularThings/IC2Classic/tree/master/src/main/java/ic2/api/classic/recipe/crafting
That is where you find all classes that a related to classics recipe. IAdvRecipe is the IC2C IRecipe Implements.
The ICraftingRecipeList gives you all the Recipes that exist but only a copy of that list. But its faster to iterate through that then checking all the recipes to find this.
Just to point this out. Its a ReadOnly API for already created recipes.
And i suggest you not to modify these recipes. Just delete them out the crafting manager and create a new one via IC2Recipe.
The only downside is that you can't read the modifier right now that can be potentionally could be added. That my fault. I fix that next patch too.

**Comment by WanionCane** [comment]
seems that I will have to create another recipe analyser XD
hey @Speiger, I don't think I will have this done until the last update, you mind if I delay it a bit?
otherwise the next update would take much longer than it should, and I have to release some new integrations for 1.11.2 asap.

**Comment by Speiger** [comment]
Well make a patch that fixes the crash for now. Thats all i ASK for.

**Comment by WanionCane** [comment]
okay =P

**Comment by WanionCane** [comment]
sorry for the dalay.
I had to disable the default IC2 integration when IC2 Classic is detected.
I will work on a better integration for IC2 Classic soon.
here's the fix:

[UniDict-1.10.2-2.9b](https://minecraft.curseforge.com/projects/unidict/files/2437552)

**Comment by grydian** [comment]
Thanks it all loaded up.  Can't wait for the final integration.  Great work!
