### ISSUE TITLE
Thermal Foundation/Expansion doesn't respect the prioritylists

### ISSUE THREAD

**Issue by CottonCthulhu** [WanionCane/UniDict#28]
Version: 

- UniDict-1.11.2-1.1

- WanionLib-1.11.2-1.1

Forge: 1.11.2 13.20.2315

Issue: The Thermal Expansion machines don't produce the right product, according to the json-files (ingots and plates). Machines from other mods (Actually Additions, RFTools, Immersive Engineering) produce the right output.

- ThermalFoundation 1.11.2-2.2.2.4

- ThermalExpansion 1.11.2-5.2.3.6

The jsonfiles:
[specificKindSorting](https://pastebin.com/PtMS2PRb)
[specificEntrySorting](https://pastebin.com/Xj7tjVsR)

Maybe it's a problem on my side, i tried to minimize the possibility of that. The log file doesn't say anything either.

**Comment by WanionCane** [comment]
I will take a look tomorrow, thanks =P

**Comment by CottonCthulhu** [comment]
I tinkered a littlebit and lunched an instance with just IE and the Thermal mods (now ThermalFoundation 1.11.2-2.2.3.5), with the same results.

For the sake of science i removed IE and replace it with Embers (modified the configs accordingly) and Embers only produced the Foundation-Ingots. I must admit, i didn't expected that to happen.

I hope that helps a tiny bit.

Thanks for your hard work! :D

And for the sake of complition too, here's the modlist: (http://modlister.com/user/CottonCthulhu)

**Comment by CottonCthulhu** [comment]
You solved the problem!
Thank you very much!

**Comment by WanionCane** [comment]
you're welcome =D
