### ISSUE TITLE
JEI doesn't work anymore in the latest version

### ISSUE THREAD

**Issue by fangedhex** [WanionCane/UniDict#29]
UniDict doesn't hide anymore the removed items :(

It seems that JEI use now : 
`IIngredientRegistry itemRegistry;
itemRegistry.removeIngredientsAtRuntime(ItemStack.class, stacksToHideList);`

I tried to update your code on my fork but it doesn't work ...
So if you have any idea how to fix that hiding, it will be cool :D

**Comment by WanionCane** [comment]
the issue was [this](https://github.com/WanionCane/UniDict/commit/48ba083545c4a56949b0666877cc66ff11972ac6#diff-295db4f88c059e563a1af222a0c1505eR79) =/

**Comment by fangedhex** [comment]
The great & old issue lol :P
