### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by ghost** [WanionCane/UniDict#30]
I hope this will an easy to implement suggestion =)

Was having trouble integrating Immersive Engineering (IE) with Big/Extreme Reactors (BR).  It was just a cluster all around hah.  I was trying to keep both but different settings in the config would remove one or the other.

IE has ores/ ingots/ nuggets/ dusts all registered as oreUranium.  This was OK.  BR's ore though was oreUranium, oreYellorite and oreYellorium where all the rest of the resources are only oreYellorium.  I tried using the config section for OreDicts before processing but it only adds.

    # Format:
    # weirdStone+minecraft:stone#1
    # The example above will register Granite as weirdStone. [default: ]
    S:userRegisteredOreDictEntries <
     >

It would be nice to have remove from OreDict as well:
oreUranium-bigreactors:brore#0
oreYellorite-bigreactors:brore#0

I really like this mod.  It's a total beast.  Thanks for all the hard work!

[Edit]
I am on 1.10.2 using ver 2.9b if it helps...

**Comment by WanionCane** [comment]
hello =P
so, you want a config to remove things from ore dictionary too?

**Comment by ghost** [comment]
I like my NEI/ JEI interface as clean as I can get it.  I have disabled all duplicate ores from generating but NEI/ JEI still showed them -- until UniDict that is.  All thanks to the config -> B:keepOneEntry=true.
But, with the above OreDict entries, this same setting also removes either the Uranium Ore or the Yellorite Ore depending on my ModID sort list.

There are config options for blacklisting items/ entries from auto hiding but they both state explicitly they only work if keepOneEntry is false.

So yeah.  I thought perhaps being able to remove from the OreDict before processing would be an easy solution.

**Comment by ghost** [comment]
It should be noted I found a work around.  I simply disabled UniDict's ability (through the configs) to autohide and I did all the hiding manually.  Worked rather well just took a while to sift through everything.  Rather not do it again if I could have it automated =)

**Comment by WanionCane** [comment]
soryr for this huge delay, I was really busy =/
I am going to implement this on the next release.

**Comment by WanionCane** [comment]
okay, I made it =P
[UniDict-1.12.2-1.2.jar](https://minecraft.curseforge.com/projects/unidict/files/2497469)
