### ISSUE TITLE
[Question] "Sub-Owner" Settings

### ISSUE THREAD

**Issue by Elvarion** [WanionCane/UniDict#33]
Found this marvelous mod and dont really understand how Ive played minecraft without it to be honest. It makes recipes and everything just so simple. Thanks for an awesome mod!

_TL:DR :p
Want Immersive Plates, But Thermal Ores/Ingots. How to?_

My question is regarding the following settings

    # enabling this allow you to specify the "owner" of each entry.
    # it also will make "S:ownerOfEveryThing" be ignored for this entry. [default: false]
    B:enableSpecificEntrySort=false

    # enabling this allow you to specify the "owner" of each kind.
    # it also will make "S:ownerOfEveryThing" be ignored for this kind. [default: false]
    B:enableSpecificKindSort=false

I really enjoy the style of the Immersive Engineering Plates for example and would Love for them to be shown instead of the Thermal Expansion Plates.
I could achieve this by setting IE as the "Master Owner" in the config.
However this made it so IE also is the "Master Owner" of all the ores it provides.
And I prefer the look of of the ores from Thermal Expansion since they are easier on the eye (for me)

How would I go about getting the changes I want?
I do understand I should add something like "immersiveengineering:plate" or similar to the "each kind" setting,  but im not sure about the formatting of doing so and would love some help! :)

Thanks
With regards, Elvarion

**Comment by WanionCane** [comment]
thanks =P

you must enable "enableSpecificKindSort", then let it run once, then it will generate a .json file, and a example file, then you follow the steps on the formating guide.
you can also enable "enableSpecificEntrySort" too, it will have priority over  "enableSpecificKindSort"

**Comment by Elvarion** [comment]
Wow that was very simple.. If I had noticed the json file and the guide I could have noticed that myself.
Feel a bit stupid now :p
But thanks alot non the less, fast reply and good documentation.
Keep up the good work!

Closing this, Question answered :)
