### ISSUE TITLE
[1.12.1 ]Immersive Engineering Press not working fully

### ISSUE THREAD

**Issue by Chenjox** [WanionCane/UniDict#35]
If I install UniDict in my modpack, i cannot press gears at the mechanical press.
The affected mods I use concerning your mod:

Embers
TechReborn
Thermal Expansion/Thermal Foundation
Forestry

Thank you for your help in advance.
Chenjox

**Comment by OrdinatorStouff** [comment]
I seemed to have experienced this. Disabling `B:ImmersiveEngineering=false` in IntegrationModule config seems to make things functional again for now but is not optimal

**Comment by WanionCane** [comment]
sorry for the delay =/
will take awhile, but I will take a look at this.

**Comment by Flanks255** [comment]
I ran into this as well, i'm using large crafttweaker scripts to dance around it.

**Comment by WanionCane** [comment]
this should have been fixed with the newest release, let me know if didn't =P
