### ISSUE TITLE
[1.12.1] "serious programming error"

### ISSUE THREAD

**Issue by UnPure** [WanionCane/UniDict#37]
While starting a server/client, UniDict is producing a fatak error.
I'm not sure if this is inteded to be like this, but the error stills doesnt look good.

    [Server thread/FATAL] [FML]: Detected an attempt by a mod FMLMod:unidict{1.12.1-1.0} to perform game activity during mod construction. This is a serious programming error.

**UniDict:** 1.0
**Forge:** 14.22.0.2475

**Comment by WanionCane** [comment]
I really don't know what this serious programming error may be, but anyway, I will take a look, but may take awhile.

**Comment by WanionCane** [comment]
let me know if it is still happening with the newest UniDict version. though, I ain't sure yet what this serious programming error may be lol.

**Comment by trienow** [comment]
Whatever it was, it works for me now!
