### ISSUE TITLE
Request - Port to MC-1.12.2 and Forge 93

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [WanionCane/UniDict#39]
I have a lot of tech mods this would be awesome ^_^

**Comment by C0rn3j** [comment]
This mod doesn't work on 1.12.2? I thought the download is just badly marked(for 1.12.1).

**Comment by WanionCane** [comment]
sorry for the lack of updates, I was really busy.
[UniDict-1.12.2-1.1b.jar](https://minecraft.curseforge.com/projects/unidict/files/2497285).
