### ISSUE TITLE
1.12.2 Immersive Engineering incompatibility

### ISSUE THREAD

**Issue by volfster** [WanionCane/UniDict#40]
As the title says: if UniDict is running alongside Immersive Engineering, IE machines stop recognizing anything besides players and cobblestone. Running with ONLY IE and UniDict can replicate this (and disabling UniDict fixes it).

Specs:

Minecraft 1.12.2
Forge 14.23.0.2522
IE 0.12-74 OR IE 0.12-73
UniDict 1.12.2-10
WanionLib 1.12.2-1.0

**Comment by WanionCane** [comment]
sorry =/
[UniDict-1.12.2-1.1.jar](https://minecraft.curseforge.com/projects/unidict/files/2497069) fixes this issue.
