### ISSUE TITLE
Unidict-1.12-1.1 makes gold nuggets craftable from nothing

### ISSUE THREAD

**Issue by Partonetrain** [WanionCane/UniDict#41]
![https://user-images.githubusercontent.com/19861808/32409690-7b26c38a-c17e-11e7-9f49-3cd2098fbcbe.png](https://user-images.githubusercontent.com/19861808/32409690-7b26c38a-c17e-11e7-9f49-3cd2098fbcbe.png)

Not a clue why. I will attach the whole log when I find it; I made several instances trying to find the culprit of this bug and I'm not sure where the log with this bug is on my hard drive.

**Comment by WanionCane** [comment]
thanks, I will take a look.

**Comment by WanionCane** [comment]
Fixed in [1.12.2-1.1b](https://minecraft.curseforge.com/projects/unidict/files/2497285)
