### ISSUE TITLE
[1.11.2] Forestry integration

### ISSUE THREAD

**Issue by Mythos** [WanionCane/UniDict#43]
Hey there, could you please integrate forestry also in 1.11.2?

At the moment we have 2 copper ingots for example, one coming from Forestry and one is from Thermal foundation. (AFAIK IC² which we also have installed also adds Copper ore)
So I think the copper ingot from "Thermal foundation" is the unified one as I don't have one from IC².

Just the one from Forestry is not being unified. :-(

**Comment by WanionCane** [comment]
there you go [UniDict-1.11.2-1.2.jar](https://minecraft.curseforge.com/projects/unidict/files/2497518)
Curse is delaying a lot today to approve the files, so, you can download it [here](https://github.com/WanionCane/UniDict/releases/tag/UniDict-1.11.2-1.2)

**Comment by Mythos** [comment]
Thanks for the quick update! :-)

**Comment by WanionCane** [comment]
you're welcome =)

**Comment by Mythos** [comment]
Hey there, with 1.2 I'm still getting 2 different copper ingots, one from Forestry and one from Thermal Foundation.... same with Tin ingots :-(

**Comment by WanionCane** [comment]
oh, so, this is happening in a machine? if yes, which machine/mod?

**Comment by Mythos** [comment]
I'm seeing those 2 ingots each with [JEI](https://minecraft.curseforge.com/projects/just-enough-items-jei)

Or am I getting the mod wrong? :D

**Comment by WanionCane** [comment]
oh, UniDict affects mainly the recipes, but it also should hide the unused variations on JEI, but seems to be not working =/
