### ISSUE TITLE
UniDict adding Gear Recipes that aren't removed by CraftTweaker

### ISSUE THREAD

**Issue by KAfable** [WanionCane/UniDict#44]
This is verison 1.1b for MC1.12.2 - it adds two gear recipes, one using 4 nuggets in all cardinal directions and an ingot to make one year and another to make 9 ingots using a block and an ingot on each side. These recipes are don't seem to be detected/removed by CraftTweaker, and it seems that UniDict is adding them, how do I remove it?

**Comment by WanionCane** [comment]
it should be able to remove recipes =/
in MC 1.12.2 CraftTweaker is still using the <Itemstack:output> to remove recipes? or it changed to recipe names?

**Comment by Blatts12** [comment]
After disabling crafting module everything works.

**Comment by SnowShock35** [comment]
@WanionCane I too am having this issue with the Direwolf20 mod pack. Really quite frustrating. I assume it's because of mod loading order.

**Comment by justinrusso** [comment]
@WanionCane CraftTweaker supports removing by IItemStack still, but also supports recipe names.

I also was not able to remove recipes added by UniDict using CraftTweaker. I ended up just disabling Crafting Integration (#52)

**Comment by WanionCane** [comment]
unfortunately, there is no way to make Craft Tweaker be able to remove UniDict generated recipes, accordinly to [Craft Tweaker Wiki](http://crafttweaker.readthedocs.io/en/latest/#Getting_Started/#scripts), it is now loading scripts on PreInitialization, and UniDict adds it's recipes on PostInitialization.
so, I had to add a way to UniDict itself be able to remove recipes, [UniDict-1.12.2-1.5.jar](https://minecraft.curseforge.com/projects/unidict/files/2506508).
even though I couldn't fix the issue (make Craft Tweaker be able to remove UniDict recipes) I think it is enough to call this fixed, right?
so, I am closing this.

**Comment by SnowShock35** [comment]
Thank you for fixing this @WanionCane Though, I will say, loading recipes in post init is bad practice, all recipes should be loaded pre init and at the latest init. However, it's not such a big deal with 1.13 around the corner where all recipes will be post init :-)

**Comment by WanionCane** [comment]
long ago I did tried to run it on init, but later I found out that some mods were adding recipes on post init, so, this was the solution, it didn't had any negative effects at the time... =/

**Comment by SnowShock35** [comment]
@WanionCane Also, not too clear on how to remove recipes with spaces at the end do I use `"` around the name?

**Comment by SnowShock35** [comment]
e.g. https://ss.blamesnow.co.uk/2017/12/1512422715-c941d771.png

**Comment by WanionCane** [comment]
I tried here with
        "unidict:gearcopper_x3_shape. a aba a "
and it is working, the reason to need the " " is, somehow, when a "Configuration" reads the parameter, idk why, it kinda does a trim on spaces, so, using " recipeName " is guaranteed that the spaces at the end of the name will remain there lol
this is just temporary, I will add a better way for doing this in the future.

**Comment by SnowShock35** [comment]
Oh you need the unidict mod prefix bit. Ah!

**Comment by WanionCane** [comment]
yeah it is needed to create the ResourceLocation =)

**Comment by SnowShock35** [comment]
@WanionCane So this is correct now? https://ss.blamesnow.co.uk/2017/12/1512423425-cfdda5fe.png

**Comment by WanionCane** [comment]
after shape you must use a "." instead of ","
oh, it work for all recipes, not just UniDict recipes lol

**Comment by SnowShock35** [comment]
oh okay. and cool! 👍

**Comment by WanionCane** [comment]
hey @SnowShock35, your mod saved my life a few days ago lol
I was needing a mod to see the OreDict entries on the item tooltips then I found yours, thanks a lot =P

**Comment by SnowShock35** [comment]
@WanionCane That's fab to hear :smile:
