### ISSUE TITLE
[Suggestion] Add a config to blacklist integration with mods

### ISSUE THREAD

**Issue by 016Nojr** [WanionCane/UniDict#46]
Can you add a config so it's possible to blacklist entire mods so UniDict doesnt touch stuff from that mod at all?

**Comment by WanionCane** [comment]
In which way? machines? items?

**Comment by 016Nojr** [comment]
Items if possible

**Comment by WanionCane** [comment]
sorry but I still don't get what you mean, if you're referring to disable integration, there is already this possibility, check "config/unidict/IntegrationModule.cfg"

**Comment by TonRZN** [comment]
If you want to UniDict to stop messing with recipes from one mod, now you can disable specific mod id's in the config file.
UniDict can also disable specific recipes if is that what you want.
