### ISSUE TITLE
[1.12.2]Recipe Conflict

### ISSUE THREAD

**Issue by drakray** [WanionCane/UniDict#47]
Unidict change some of BaseMetal Rod recipe to side-by-side ingot instead of over-one-another, which conflict with BM pressure plate recipe

**Comment by WanionCane** [comment]
oh weird, could you send some screenshots?

**Comment by drakray** [comment]
![2017-11-20_15 24 19](https://user-images.githubusercontent.com/4303126/33039924-a3283680-ce07-11e7-942e-a2c5d9490030.png)
![2017-11-20_15 24 27](https://user-images.githubusercontent.com/4303126/33039925-a3406d36-ce07-11e7-9c50-d3f5984d1ca5.png)
![2017-11-20_15 24 39](https://user-images.githubusercontent.com/4303126/33039926-a34f628c-ce07-11e7-8f62-da8ef22577b9.png)
![2017-11-20_15 24 59](https://user-images.githubusercontent.com/4303126/33039927-a35ea3b4-ce07-11e7-822c-0a44ce213615.png)
![2017-11-20_15 25 10](https://user-images.githubusercontent.com/4303126/33039928-a36c8f74-ce07-11e7-87fc-2cb05bfcff58.png)
![2017-11-20_15 25 16](https://user-images.githubusercontent.com/4303126/33039929-a37e5f74-ce07-11e7-8aef-7d11ec29ceef.png)
![2017-11-20_15 25 40](https://user-images.githubusercontent.com/4303126/33039930-a3903118-ce07-11e7-89b4-df77e1530b95.png)
![2017-11-20_15 25 42](https://user-images.githubusercontent.com/4303126/33039931-a39f5648-ce07-11e7-93f4-c67a4ffa07c3.png)
![2017-11-20_15 25 45](https://user-images.githubusercontent.com/4303126/33039932-a3adae46-ce07-11e7-96ae-8fdf37a90cf4.png)
![2017-11-20_15 25 50](https://user-images.githubusercontent.com/4303126/33039933-a3c3a5c0-ce07-11e7-9045-d97d16f30183.png)
![2017-11-20_15 25 55](https://user-images.githubusercontent.com/4303126/33039934-a3d32180-ce07-11e7-9fd8-a65e6cac0ff3.png)
![2017-11-20_15 25 58](https://user-images.githubusercontent.com/4303126/33039935-a3e4980c-ce07-11e7-830e-131218750df4.png)

**Comment by drakray** [comment]
1st sc show unmodified BM rod recipe, second show yours
Below those is more to show conflict, which is more visible with NoMoreRecipeConflict mod

**Comment by drakray** [comment]
To show that some normal BaseMetal Rod Recipe are changed, copper don't work:
![2017-11-20_15 35 23](https://user-images.githubusercontent.com/4303126/33040299-a25e2d76-ce08-11e7-9981-dd09d24559a0.png)

**Comment by WanionCane** [comment]
this is really a problem, I will fix this ASAP, thank you, you helped a lot! =P

**Comment by drakray** [comment]
No problem, I like finding these kind of bug in others code, make me forget about my own lol XD

**Comment by WanionCane** [comment]
Fixed on the lasted [WanionLib-1.12.2-1.2c](https://minecraft.curseforge.com/projects/wanionlib/files/2502209)

**Comment by WanionCane** [comment]
it has been fixed, right?

**Comment by drakray** [comment]
testing rn

**Comment by drakray** [comment]
Almost work correctly, but only work on 3x3, as a ShapedMirrored like
`x--`
`x--`
`---` 
![2017-11-22_11 54 05](https://user-images.githubusercontent.com/4303126/33139911-90191eb2-cf7c-11e7-87b4-37fb75e90065.png)
![2017-11-22_11 54 12](https://user-images.githubusercontent.com/4303126/33139912-906f3a5e-cf7c-11e7-832e-a07496e685d3.png)
![2017-11-22_11 54 18](https://user-images.githubusercontent.com/4303126/33139913-90eaa504-cf7c-11e7-9dfb-1ae2c086b7d3.png)
![2017-11-22_11 55 55](https://user-images.githubusercontent.com/4303126/33139914-9115fda8-cf7c-11e7-94b6-5abec49a7e11.png)
![2017-11-22_11 56 12](https://user-images.githubusercontent.com/4303126/33139915-91214da2-cf7c-11e7-93af-31817c30265a.png)

**Comment by WanionCane** [comment]
oh crap :scream:

**Comment by drakray** [comment]
still, a step in the right direction :D (no more conflict, just can't craft in hand, so no rush)

**Comment by WanionCane** [comment]
true, I guess I will have to use somethings that I had to learn when I made [Bigger Crafting Tables](https://minecraft.curseforge.com/projects/bigger-crafting-tables) to fix this other issue lol
so, since this issue is fixed, I am closing this =)
thanks for your help =P

**Comment by drakray** [comment]
No problem, will keep you in touch if/when something change

**Comment by WanionCane** [comment]
hello again, I released a new version of UniDict & WanionLib, I think I fixed this other issue, could you try with it please?

**Comment by drakray** [comment]
Is fixed :D

**Comment by drakray** [comment]
Is fixed :D
![2017-11-28_16 44 33](https://user-images.githubusercontent.com/4303126/33346791-dd58289e-d45e-11e7-8168-0c75eec5fa31.png)

**Comment by WanionCane** [comment]
yay =D
