### ISSUE TITLE
[Suggestion] keepOneEntry whitelist for certain oredict

### ISSUE THREAD

**Issue by Blatts12** [WanionCane/UniDict#49]
e.g.
ingot*
gear*
plate*

**Comment by WanionCane** [comment]
it is a good idea, though, no promises.
thanks =P

**Comment by WanionCane** [comment]
oh noo I made a black list T.T
sorry =/
the next version I will add a config to convert this "Black List" into a "White List".

**Comment by WanionCane** [comment]
done, [UniDict-1.12.2-1.9.jar](https://minecraft.curseforge.com/projects/unidict/files/2512252).
sorry for initially making a black list, but, I guess it may be useful for someone, right? XD

**Comment by Blatts12** [comment]
.# entries listed here will be blacklisted in keepOneEntry.
    # must be the exact entry name. [default: ]
    S:keepOneEntryEntryBlackList <
     >

    # kinds listed here will be blacklisted in keepOneEntry.
    # must be the exact kind name. [default: ]
    S:keepOneEntryKindBlackList <
     >

    # mods listed here will be blacklisted in keepOneEntry.
    # must be the exact modID. [default: ]
    S:keepOneEntryModBlackList <
     >

Sooo, where can i put oredicts?

**Comment by WanionCane** [comment]
it is on the "S:keepOneEntryEntryBlackList"

**Comment by Blatts12** [comment]
.# enable this if you want the keepOneEntry blacklists to became whitelists.
    #  [default: false]
    B:keepOneEntryBlackListsAsWhiteLists=true

    # entries listed here will be blacklisted in keepOneEntry.
    # must be the exact entry name. [default: ]
    S:keepOneEntryEntryBlackList <
	gearCopper
     >

This does not work like neither the blacklist nor the whitelist.

**Comment by WanionCane** [comment]
have you enabled keep one entry? "B:keepOneEntry"

**Comment by Blatts12** [comment]
Yes

**Comment by WanionCane** [comment]
sorry, I really should test things a bit more intensively before releasing =/
[UniDict](https://minecraft.curseforge.com/projects/unidict/files/2512456)

**Comment by Blatts12** [comment]
Thank You very much for your work.
