### ISSUE TITLE
[Bug 1.10.2-1.5]Dirty Iron dust is not usable in Enrichment Chamber.

### ISSUE THREAD

**Issue by AlphaKintari** [WanionCane/UniDict#5]
Sounds like a Mekanism problem, but its an interesting issue:

If you have both UniDict-1.10.2-1.5 and industrialcraft-2-2.6.37-ex110 in your modpack, Dirty Iron Dust will not process in the Enrichment Chamber.  Other dusts seem to work fine, tested gold, osmium, lead, copper,and tin all work fine. 

With just IC2, no UniDict, no issues.
With just UniDict, no IC2, no issues.

Using the default configuration file for all mods.
Its the combination of both of these that seems to cause an issue, leaning towards UniDict because of the way that it changes the dusts. 

[Mekanism issue for referance](https://github.com/aidancbrady/Mekanism/issues/3566)

**Comment by WanionCane** [comment]
sorry for the late reply.
this is really weird, UniDict don't does anything with the Dirty dusts.

**Comment by AlphaKintari** [comment]
no worries, I can send you a testing instance if you would like, it's an odd issue surely. But my guess is that it has something to do with the interaction between the two mods.

**Comment by WanionCane** [comment]
thanks, but there is no need.
I think that after UniDict sort the entries, Mekanism is not recognizing the new entry and is not registering his own dirty dust, lol.

**Comment by AlphaKintari** [comment]
heh... I can code in JAVA, but I have little to no experience (alright, no) in how the minecraft ore dictionary works.  Who needs to look at this?  You or @aidancbrady?

**Comment by Utildayael** [comment]
Same issue. I had an issue logged with Mekanism but Aidan closed it out as crossmod problem. Glad to hear someone figured out WHAT is causing it but yes, curious who the fix request needs to go to as well.

Thanks

**Comment by WanionCane** [comment]
It may be UniDict fault, I'm going to do some rewrites in the next few days, may solve this issue, and sorry for how long took to I do something.

**Comment by Utildayael** [comment]
Thanks for looking into it! :)

**Comment by WanionCane** [comment]
after some rewrites, was indeed UniDict fault, I'm really sorry...

**Comment by Utildayael** [comment]
No worries. Thank you for fixing it!! :)

**Comment by mainframecn** [comment]
Nice, hope to see the new build soon. I am having the same issue and like to keep using unidict.

**Comment by WanionCane** [comment]
could you guys try with this? [UniDict-1.10.2-1.8c](https://github.com/WanionCane/UniDict/releases/tag/UniDict-1.10.2-1.8c).

1.7.10 release is coming soon.
edit: [UniDict-1.7.10-2.9.1](https://github.com/WanionCane/UniDict/releases/tag/UniDict-1.7.10-2.9.1)

**Comment by mainframecn** [comment]
Seems to be working for me now. Thanks for the quick support!

**Comment by WanionCane** [comment]
not so quick actually XD
