### ISSUE TITLE
UniDict not behaving properly with Astral Sorcerys ore generating thingy (image included)

### ISSUE THREAD

**Issue by 1persON768** [WanionCane/UniDict#50]
https://puu.sh/yuIBM/c227744b49.png

When you mine the stone in the middle it generates random ore in place of it, it has given me lead copper and tin from NuclearCraft, Aluminum from Vulpes and Nickel from Immersive Engineering

MC version 1.12.2 forge-14.23.0.2551
UniDict version 1.12.2-1.2

**Comment by WanionCane** [comment]
so you want it to generate ores from just one mod?
if yes, then it probably requires an integration, but depending on how the mod has been written, it may not be possible.

**Comment by 1persON768** [comment]
Yes, that is how I thought UniDict should handle ores from all the different mods.
Do you need anything else from me regarding this issue?

**Comment by WanionCane** [comment]
sorry for the huuuuge delay guys, awhile ago I took a look on Astral Sorcery, and it seems that the only way to make this work is by setting keep one entry to true.

so, I am closing this, and again, sorry for the delay =/
