### ISSUE TITLE
UniDict Recipes Cannot Be Removed by CraftTweaker

### ISSUE THREAD

**Issue by justinrusso** [WanionCane/UniDict#52]
Hello there and thank you for this useful mod!

I'm wanting to use UniDict to unify the output of machines, but I don't want the recipes that UniDict adds, as I'd prefer to define them myself. When using CraftTweaker, removing the recipes of, for example, `<minecraft:iron_block>` (`recipes.remove(<minecraft:iron_block>);`), removes all but the UniDict recipe entry. Would you be able to fix it so UniDict recipes can be removed?

Thank you for your time!

**Comment by justinrusso** [comment]
Ah... I see there is a crafting module. Probably what I need to disable.

**Comment by WanionCane** [comment]
yeah, that is what you need to disable.
