### ISSUE TITLE
Net Loss Ore Recipes

### ISSUE THREAD

**Issue by Shahelion** [WanionCane/UniDict#55]
I assume the recipes that call for two of the same ore are meant to manually unify the ores in question, but they take two and only give one in return.

![2017-12-08_00 22 28](https://user-images.githubusercontent.com/6917535/33757182-e7225b82-dbad-11e7-9a4b-6c3c962d26d1.png)

**Comment by WanionCane** [comment]
I am 99.999% sure that isn't UniDict fault, but, could you disable Crafting Integration in (confog/unidict/IntegrationModule.cfg) to see if this is still happening? if it is, then isn't UniDict fault.

**Comment by WanionCane** [comment]
any news?

**Comment by Shahelion** [comment]
A: Disabling that in the config removed the recipe

B: The tooltip of the resulting ore block says "Recipe added by UniDict"

**Comment by WanionCane** [comment]
well, I consider the Crafting Integration the most important part of this mod, so keeping it disabe is almost like the entire mod has been disabled lol.
so, could you try that recipe on your Crafting Table? even though the recipe added by UniDict disapeared, it is probably still in the game, though, not Created by UnIDict.
if, it is still outputting one ore for every two input ores, then isn't UniDict fault.

**Comment by Shahelion** [comment]
The recipe isn't there anymore with that option disabled, and with it enabled, it acts as it shows, giving one ore for two.

**Comment by WanionCane** [comment]
the way Crafting Integration works is, it fixes existing recipes, it can not create new recipes, so to a recipe be re-created by UniDict, it must have existed before, there is no hardcoded recipes on Crafting Integration.
also, it is absolutely impossible for it to change the output stack size to 1, instead of 2, so the original recipe probably also outputs 1 instead of 2.

**Comment by Shahelion** [comment]
I don't know what else to say, just that without that part of this mod enabled, the recipe does not exist at all. JEI is clear that this mod is creating the recipe.

**Comment by WanionCane** [comment]
UniDict is indeed creating this recipe, but it is based in a previous recipe.
