### ISSUE TITLE
[1.12.2] Suggestion for Immersive Engineering Alloy Kiln Unification

### ISSUE THREAD

**Issue by AcidKat** [WanionCane/UniDict#56]
Noticed that the IE alloy kiln doesn't play nice with the Ore Dictionary and IE's Craft Tweaker functions aren't working so great at the moment either. Would it be possible to force the Kiln to respect ore dictionary? 

Specifically I'm talking about Constantan and Electrum which don't work correctly when messing with the ore dictionary (I use the "keep one entry" setting, which is such a great feature btw <3), it seems that IE just outputs IE Electrum and Constantan even when they are removed from the ore dictionary, which naturally makes them useless.

Just a note here: I was gonna ask the IE devs directly about this but after a bit of digging around in their issue tracker a bit I realised they seemed a bit touchy about removing ore dictionary entries etc... so I figured it was probably not a good idea to poke the bear.

**Comment by WanionCane** [comment]
Implemented on [UniDict-1.12.2-1.6](https://minecraft.curseforge.com/projects/unidict/files/2508665)
