### ISSUE TITLE
Block Cutting Machine

### ISSUE THREAD

**Issue by MakerTim** [WanionCane/UniDict#57]
Hey,
I just noticed that you dont handle the Block Cutting Machine from IC²
There you can change blocks (gold/copper/iron...) directly into plates

Hope this is a small thing to fix 👍 
Tnx for this awesome mod <3

**Comment by WanionCane** [comment]
yeah this can easily be implemented, thanks for your suggestion =P

**Comment by WanionCane** [comment]
Implemented on [UniDict-1.12.2-1.6](https://minecraft.curseforge.com/projects/unidict/files/2508665)
