### ISSUE TITLE
Add Extra Utilities Integration ?

### ISSUE THREAD

**Issue by TonRZN** [WanionCane/UniDict#58]
Is Extra Utilities furnace/crusher integration possible in the mod? 

Sorry if my english is bad, I'm brazilian :P

**Comment by WanionCane** [comment]
achava que não precisava, porém parece que precisa =P
vou dar uma olhada, assim que possível eu faço.
obs: também sou brasileiro

**Comment by WanionCane** [comment]
desculpe a demora, eu estava meio ocupado com outras coisas.
então, eu dei uma olhada, e parece não precisar de uma integração.
se possível, teria como anexar uma Screenshot do "problema"?
se quiser, me adiciona no Twitch App, é o mesmo nickname que aqui.
facilitaria muito =P

**Comment by TonRZN** [comment]
Por exemplo: se você colocar um minério do mekanism no crusher, ele vai te dar o dust do mekanism, mas se você colocar do ic2 vai te dar o dust do ic2

Vou te adicionar la. E desculpa, meu teclado não tem acento kkk

**Comment by WanionCane** [comment]
estranho, vou dar uma olhada melhor =P
