### ISSUE TITLE
Latest version of Tinkers appears to have broke integration 1.12.2

### ISSUE THREAD

**Issue by tgstyle** [WanionCane/UniDict#59]
TConstruct-1.12-2.8.0.45.jar

Nothing is coming out from the mod(s) specified, previous version works fine.

**Comment by WanionCane** [comment]
I will take a look =P

**Comment by WanionCane** [comment]
seeing their changelog, I saw this:
> - New ore preference config. This is a list of mod IDs to prefer for recipe outputs from the ore dictionary, such as casting recipes.

this is probably related and the cause for this issue, UniDict never had integration with Tinkers Construct, but now seems that it will need to have one.

**Comment by WanionCane** [comment]
so, a temporary solution for this would be removing all the entries on "S:orePreference" in the tconstruct.cfg.
the next mod version (1.12.2-1.9) will have a better solution for this.
