### ISSUE TITLE
[Feature Request] Immersive Engineering support

### ISSUE THREAD

**Issue by erindal** [WanionCane/UniDict#6]
IE for 1.10.2 is now out, so whenever you get the chance, adding support (mostly for the metal press) would be greatly appreciated.

**Comment by WanionCane** [comment]
I'm working on it :)

**Comment by WanionCane** [comment]
it is done, [b25ea05](https://github.com/WanionCane/UniDict/commit/b25ea055113e0839374e8d9e5fa7d6bc7e7f5715).

**Comment by WanionCane** [comment]
[UniDict-1.10.2-1.6.](https://minecraft.curseforge.com/projects/unidict/files/2325743)

**Comment by erindal** [comment]
Wow you're fast! Thank you!

**Comment by WanionCane** [comment]
you are welcome =)
