### ISSUE TITLE
plate crafting by unidict is wrong?

### ISSUE THREAD

**Issue by Leftorius** [WanionCane/UniDict#61]
here some screenshots:
https://imgur.com/a/Lbaax

materials:
- copper
- tin
- bronze
- silver
- lead
- iron
- gold
- steel

Problem is, I can't even disable it with CraftTweaker, unless I try to disable all recipes from unidict and thats not the point.

it's this modpack (mine):
https://minecraft.curseforge.com/projects/minecraft-engineer

**Comment by WanionCane** [comment]
omg.. this is very concerning, but anyway, CraftTweaker can't remove UniDict created recipes, because CraftTweaker now runs their scripts on preInit.
so, in order to remove UniDict created recipes, you must use the "S:recipeToRemoveList" on UniDict.cfg

**Comment by Leftorius** [comment]
I mean it's still an dev pack, so if you can fix it internally, I would be more helpfull then fixing it via crafttweaker :D

**Comment by WanionCane** [comment]
I will take a look on it really soon.

**Comment by WanionCane** [comment]
I am not being able to install your pack =/
it is saying that the name of the file, or the directory name, or both, is too long.

**Comment by Leftorius** [comment]
If someone else gets this error and has PrimalCore installed, look into the configs/primal/primal.cfg for this line and set it to false:

    # Enable gallagher Recipes for metal plates, these are registered with the ore dictionary as plate[Name].
    B:ENABLE_GALLAGHER_PLATES=true 


set               B:ENABLE_GALLAGHER_PLATES=false
