### ISSUE TITLE
Mekanism adds recipes with higher priority

### ISSUE THREAD

**Issue by WeaselOnaStick** [WanionCane/UniDict#62]
![This happens](https://user-images.githubusercontent.com/10953814/34210222-acca33c8-e5c7-11e7-8fbb-ef1336f3fa3c.png)

**Comment by WanionCane** [comment]
unfortunately, Mekanism has their own implementations of IRecipe, in order to make UniDict work with them, I would have to create a specific IRecipeResearcher for these recipes.
which honestly, is a pain.
