### ISSUE TITLE
Tech Reborn + Thermal Expansion Integration Bug

### ISSUE THREAD

**Issue by HorizonsMC** [WanionCane/UniDict#63]
Hello, I have noticed that it appears unidict adds support for Tech Reborn dust to the redstone furnace but it doesn't work.

This shows in JEI:
https://i.imgur.com/vU25E6D.png

But the machine does not accept any of the dust.

It may be because advanced rocketry also adds the dust and when it unifys them it does this.

**Comment by WanionCane** [comment]
I really don't know what is causing this, are you in a server?

**Comment by WanionCane** [comment]
if it is showing on JEI, it means that the recipe is there, and if it isn't accepting the dust, it is probably something related to Thermal Expansion.
so it is not an UnIDict issue.
