### ISSUE TITLE
[1.12.2] Config got ignored

### ISSUE THREAD

**Issue by Draskh** [WanionCane/UniDict#64]
I added that: 

oreAluminum+techreborn:ore#4
oreAluminum+immersiveengineering:ore#1

to the config file but it did not work. The blocks weren't registered as Aluminum Ore.

**Comment by Draskh** [comment]
I tried to register Bauxite Ore as Aluminum Ore.

**Comment by WanionCane** [comment]
I tried here, and it is working fine, you sure that you added it to "userRegisteredOreDictEntries"?
because there is a similar config option, but to remove ore dict entriies. "userRemovedOreDictEntries".

on the next version these two options will be unified on the same option, the only way to differentiate them is the "+" and the "-" operators.

**Comment by Draskh** [comment]
Here is the complete config file converted to .txt.
[UniDict.txt](https://github.com/WanionCane/UniDict/files/1589740/UniDict.txt)

**Comment by Draskh** [comment]
All other entries I added work.

**Comment by Draskh** [comment]
Seems that something prevents the registration as oreAluminum.
https://github.com/BluSunrize/ImmersiveEngineering/issues/2728

**Comment by Draskh** [comment]
It seems to be an issue with Thermal Foundation. If it is not present registration works. https://github.com/CoFH/Feedback/issues/833

**Comment by KingLemming** [comment]
Yeah, it sure isn't an issue with Thermal Foundation.

**Comment by Draskh** [comment]
I will keep on trying to find out what causing that issue.

**Comment by WanionCane** [comment]
I have no idea about what is causing this, I tried here with several names, and I could register them, but as oreAluminum, I couldn't, so... I have no clue....

**Comment by Draskh** [comment]
Do you have Thermal Foundation present?

**Comment by WanionCane** [comment]
yeah, it is present here, probably you wants me to remove it and try again, right? XD

**Comment by Draskh** [comment]
Yes. Try to register dirt as oreAluminim with and without thermal foundation. If you have the same issue tell me.

**Comment by WanionCane** [comment]
it seems to be working for Immersive Engineering Bauxite, but not for the Tech Reborn one.
really weird, more testing will have to wait till tomorrow, good night =P
