### ISSUE TITLE
[1.12.2] Crash on MacOSX for unkonwn reason

### ISSUE THREAD

**Issue by Draskh** [WanionCane/UniDict#66]
The game crashed on my friends Macbook. 
[crash-2017-12-28_21.16.txt](https://github.com/WanionCane/UniDict/files/1592030/crash-2017-12-28_21.16.txt)

**Comment by WanionCane** [comment]
the exception seems to be "Caused by: java.lang.OutOfMemoryError: unable to create new native thread".

**Comment by Draskh** [comment]
But there is: 
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from UniDict (unidict)
Caused by: java.lang.OutOfMemoryError: unable to create new native thread

and there is Memory: 4312239864 bytes (4112 MB) / 8489271296 bytes (8096 MB) up to 8589934592 bytes (8192 MB) 
That should be enough. So why did that happen with Unidict?

**Comment by Draskh** [comment]
That always happens at the end of the start.

**Comment by WanionCane** [comment]
oh, so seems that there is available memory. but unfortunately, I don't have any mac and neither money to buy one to try to fix this =/
on this specific case, the crashlog isn't enough to figureout what is happening =/

**Comment by Draskh** [comment]
It only happens if Block Drops is present. 
https://minecraft.curseforge.com/projects/block-drops-jei-addon

I think that that was overlasting the process.

**Comment by WanionCane** [comment]
well, I really don't know why it would interfere, but okay XD
