### ISSUE TITLE
Fluid Transposer recipes are not replaced.

### ISSUE THREAD

**Issue by jkroepke** [WanionCane/UniDict#67]
Hi,

I have Mekanism choosed over Thermal Expansion in my config.

Now I got Obsidian Dust instead Pulverized Obsidian from the Pulverizer.

Now I want to make Basalz Powder in the Fluid Transposer but it requires Pulverized Obsidian. Now i'm unable to create this item.

Can UniDict support the Fluid Transposer like the Pulverizer?

**Comment by WanionCane** [comment]
I guess this Fluid transposer recipe doesn't accept Ore Dictionary?

**Comment by jkroepke** [comment]
I dont know. TE doent use JSON recipces and I do not understand the java code.

Here is the definition: https://github.com/CoFH/ThermalExpansion/blob/ec03c7180d73caa15c3b9a78feb6b58b97a02c51/src/main/java/cofh/thermalexpansion/util/managers/machine/TransposerManager.java#L137

**Comment by WanionCane** [comment]
unfortunately, it really wants the Pulverized Obsidian.
omg, Thermal Expansion is open source now? awesome!

**Comment by jkroepke** [comment]
Thanks for the clarification.

**Comment by KingLemming** [comment]
TE is NOT open source. Do not confuse visible with open.

**Comment by WanionCane** [comment]
oh okay, sorry =/
I didn't tried to create confusion.

**Comment by WanionCane** [comment]
my mistake, there is a language barrier on my side.
surely visible doesn't mean open.
