### ISSUE TITLE
[Suggestion] Add NuclearCraft Integration

### ISSUE THREAD

**Issue by HorizonsMC** [WanionCane/UniDict#69]
When using NuclearCraft and Unidict it seems to output the original version instead of the unified one if you use the nuclearcraft machines.

https://i.imgur.com/IFGUqzF.png

This is what it should be outputting if unification worked with my config setup.

https://i.imgur.com/kUiDH6L.png

**Comment by WanionCane** [comment]
it will be included on the next version, thanks for the suggestion =)

**Comment by WanionCane** [comment]
I took a look here, and it doesn't seems to need an integration.

**Comment by HorizonsMC** [comment]
Maybe they updated it, I'll check and see if it still outputs the wrong version.

**Comment by HorizonsMC** [comment]
Yes, it appears NuclearCraft updated and fixed it 👍 
![image](https://user-images.githubusercontent.com/34108658/34839959-0d96cf6a-f6c9-11e7-9f7c-684ce3cd4529.png)

One of there changes on NuclearCraft-2.8d--1.12.2 is:
* Added many more integration recipes

This version came out after my report so guessing that did it.

**Comment by WanionCane** [comment]
yay XD
I will take a look on their code to see how they made it, just for curiosity XD

**Comment by NielsPilgaard** [comment]
A lot of the Alloy Furnace recipes make IC2 ingots and blocks, even though I have Unidict set to Thermal Foundation first.
