### ISSUE TITLE
UniDict destroying Industrial Craft 2 

### ISSUE THREAD

**Issue by ghost** [WanionCane/UniDict#7]
Was having a problem where I could craft a lot of the items made with cutter/forge hammer from Industrial Craft 2, as well as other problems including not being able to craft a solid block of iron or any ore that allowed it. Had no idea what was wrong and though tit was an issue on IC2's end but then i removed UniDict and voila all my recipes worked fine in IC2 as well as the vanilla stuff it was apparently interfering with.

**Comment by WanionCane** [comment]
1.7.10 or 1.10.2?

**Comment by ghost** [comment]
1.10.2, tested on both SP and on my server

**Comment by WanionCane** [comment]
probably some ic2 update caused some malfunction, I will take a look, thanks for letting me know =D

**Comment by WanionCane** [comment]
I tried here, it is working fine, maybe you're looking for recipes of the wrong item.

**Comment by WanionCane** [comment]
could you try with this?
[UniDict-1.10.2-2.3b](https://minecraft.curseforge.com/projects/unidict/files/2337513)
it probably will fix your issue.
thanks.

**Comment by ghost** [comment]
Hey, I've since stopped using IC2 on my server, but I went ahead and tested the new version of UniDict for you with IC2 and the problems I experienced seem to have been completely fixed. Now I haven't tested it extensively, only with the problems I was previously experiencing, but I went ahead and was able to perfectly use the forge hammer/cutter with any type of ingot/plate, as well as craft solid ore blocks with any group of ingots. So as far as I can tell, the issue is fixed! Thanks for your hard work, going to go ahead and add UniDict back onto my server now since having just a single ingot for each specific ore is super useful.

**Comment by WanionCane** [comment]
awesome XD
good to see that everything is working =)
if there is anything else let me know, ok?
