### ISSUE TITLE
Failed to load world with new release

### ISSUE THREAD

**Issue by Trixz2018** [WanionCane/UniDict#72]
https://paste.ee/p/B19qT

**Comment by miuirussia** [comment]
Maybe related issue: https://github.com/MrRiegel/Yunifier/issues/11

**Comment by Trixz2018** [comment]
yes its the same issue, its between unidict and InstantUnify, going to revert back until this is fixed

**Comment by WanionCane** [comment]
I already notified MrRiegel about this =)

**Comment by WanionCane** [comment]
wasn't InstantUnify fault, I am working on a fix =)

**Comment by WanionCane** [comment]
there you go guys, sorry about this.
[UniDict-1.12.2-2.2b.jar](https://minecraft.curseforge.com/projects/unidict/files/2519382)
**fun fact**: this happened because I fixed a memory leak on the 1.12.2-2.2 version, and some things were depending on this memory leak to work lol.

**Comment by nigrum-dente** [comment]
Wut ?

Memory leak should  be bad from what I remember, like unused stuff that were not removed correctly from memory, so how does something ends up depending on a memory leak to work ?

Just curious.

**Comment by WanionCane** [comment]
I forgot to set one variable to null, in order to be garbage collected;
and one of the methods were requiring this variable to not be null;
which caused this crash.
I ain't sure how bad the leak was, because it depends on the amount of mods loaded, and so on, but it could be quite big =P

**Comment by WanionCane** [comment]
the leak was, basically, all the resource caching, all the "unifying" stuff you can imagine, and a lot of variables.

**Comment by WanionCane** [comment]
which means, almost everything of UniDict was staying on the memory after the loading stages XD
