### ISSUE TITLE
[1.12.2] [Request] Blacklist for whole modID

### ISSUE THREAD

**Issue by Draskh** [WanionCane/UniDict#73]
I have an issue with Oreshrubs. UniDict adds to many recipes for that. I would like to ask if it is possible to put a blacklist in the config that include a complete mod. 
You can see the issue here: https://github.com/Lhykos/OreShrubs/issues/17

**Comment by WanionCane** [comment]
hello, the blacklist works on the output, not on the input, so... it wouldn't change this.
but, I can create something to blacklist recipes added by certain mods :)

**Comment by Draskh** [comment]
That would be solve the problem I think and would be great.
