### ISSUE TITLE
Unidict removes some secondary outputs from Immersive Engineer's Crusher

### ISSUE THREAD

**Issue by SSyl** [WanionCane/UniDict#75]
With Unidict and Immersive Engineering using all default settings, some of the secondary outputs from the crusher get removed.

For example, without Unidict, putting iron ore in the crusher gives two iron grit and has a 10% chance for Nickel Grit as well. However, with Unidict it removes the chance for Nickel Grit to drop.

From a quick comparison, copper ore also no longer has a chance to give gold grit and uranium no longer has a chance to give lead grit.

I noticed this at first when using Unidict alongside Immersive Engineering and Thermal Foundation, but I tested it out in 1.12.2 using only Immersive Engineering + Unidict and it removed those secondary drops.

![2018-01-21_04 12 59](https://user-images.githubusercontent.com/6855315/35193045-fd9daba0-fe62-11e7-9afc-9bfbf9bfb521.png)

![2018-01-21_04 13 12](https://user-images.githubusercontent.com/6855315/35193046-032ef98e-fe63-11e7-818a-722006cd1f76.png)

![2018-01-21_04 25 29](https://user-images.githubusercontent.com/6855315/35193059-28e03fa8-fe63-11e7-82a0-800f6af55b50.png)

![2018-01-21_04 25 36](https://user-images.githubusercontent.com/6855315/35193060-28ec4230-fe63-11e7-95bc-af068e6d408a.png)

**Comment by WanionCane** [comment]
this will be fixed on the next version =)
