### ISSUE TITLE
I Cant Make The Config As I Wish

### ISSUE THREAD

**Issue by FlickySH** [WanionCane/UniDict#76]
I am trying to disable the tinker's construct aluminum brass because i already have one in modern metals.
I cant make my config to work, for some reason, when i put the mm alubrass ingot inside of a crafting table i get the tic one
I want to disable the tic alubrass completely and replace it with modern metals alubrass.

https://pastebin.com/bTvVr2un
my config

unidict 1.12.2-2.3.1
wanionLib 1.12.2-1.4

plz help, there are no tutorials for it.
Aregev2

**Comment by WanionCane** [comment]
since you already added "modernmetals" to "S:ownerOfEveryThing",
add "Alubrass" to "S:metalsToUnify"
this should be enough to make it work.
if isn't, tell me =P
