### ISSUE TITLE
Misspelled "IDUSTRIAL_FOREGOIN" in IntegrationModule

### ISSUE THREAD

**Issue by Lordmau5** [WanionCane/UniDict#77]
https://github.com/WanionCane/UniDict/blob/7cbbe9cdf51d79108cc94286c5bc9a3b20dd16a6/src/main/java/wanion/unidict/integration/IntegrationModule.java#L72

Nothing too trivial that would affect anything other than... well yea, the config which shows it like this
![image](https://user-images.githubusercontent.com/1345036/35421388-40dc5fc2-0243-11e8-8c9f-ffe7db6b869a.png)

**Comment by WanionCane** [comment]
omg, sorry XD
it will be fixed on the next version =P
