### ISSUE TITLE
UniDict Recipes in JEI not craftable

### ISSUE THREAD

**Issue by StephJ2Fan** [WanionCane/UniDict#78]
I am having an issue with my custom pack, that includes UniDict. I can see the recipe for breaking TE ore blocks into ingots, but when I go to craft it in either a TiCon or a vanilla crafting block, they will not break down. Right now for me to get ingots from block form is to smelt them back down and put them through with the ingot cast from TiCon.

https://www.dropbox.com/s/jnbyb6bh0wcqnyb/Steph%27s%20Kitchen%20Pack%20Revamped-1.51.zip?dl=0    This is a link to the modpack that I am working on. In this download is a saved world. You should be able to grab the items from JEI and see what I mean.

**Comment by WanionCane** [comment]
really weird, just to confirm, you aren't being able to craft ingots from blocks?

**Comment by StephJ2Fan** [comment]
Correct! and it seems to be the TE blocks from what I tested... Botania worked fine. Vanilla Ores worked fined.  But I can see the recipes in JEI. I can click on the plus sign to add the recipe to the crafting grid...it pulls the block form but doesn't give me an output

**Comment by NitroxydeX** [comment]
I can confirm this too.
In my example it's block of aluminum to aluminum ingots from Immersive Engineering. Showing up in JEI but it's not working in the crafting table.

**Comment by WanionCane** [comment]
sorry for the late asnwer, I couldn't find any non-craftable recipe, so I am closing this.
