### ISSUE TITLE
[1.10.2]The wrong ore dictionary name of some items!

### ISSUE THREAD

**Issue by Summpot** [WanionCane/UniDict#79]
Oak Wood Planks and apple had a wrong ore dictionary name ----ingotcopper
My version is 1.10.2-2.9b

**Comment by WanionCane** [comment]
I am pretty sure that isn't UniDict fault.

**Comment by Summpot** [comment]
You are right, the bug still exists after I disabled this mod.

**Comment by Summpot** [comment]
but I still have a problem that how to remove the wrong ore dictionary name.

**Comment by WanionCane** [comment]
you can use CraftTweaker or UniDict itself to remove these wrong entries.
