### ISSUE TITLE
Cant join vanilla servers with your mod installed

### ISSUE THREAD

**Issue by HaXrDEV** [WanionCane/UniDict#8]
Specifically SpongeForge Servers without mods. No errors are given, other than it wont let me connect unless i also have it installed on every server i want to join.

Using UniDict-1.10.2-2.3b
On Forge-1.10.2-12.18.2.2107
and spongeforge-1.10.2-2098-6.0.0-BETA-1823

**Comment by WanionCane** [comment]
UniDict isn't a client side only mod, it must be installed on the server too.

**Comment by HaXrDEV** [comment]
Sorry for not explaining myself clearly. The issue is when installed on the client i wont be able to connect to my hub server, which is vanilla.

**Comment by WanionCane** [comment]
the hub server has to have UniDict too.

**Comment by HaXrDEV** [comment]
No! The point is to have vanilla and modded servers working together in a bungee network. What you propose would not let my vanilla players enter the network at all. I'm sorry, but your amazing mod is the only one which does this. 
You dont sound interested in helping fixing my issue, leaving me with no other choice but to remove your mod. Which i think is rather sad :/

**Comment by WanionCane** [comment]
I will add a config option to ignore the requirement of UniDict being present on the the server.

**Comment by HaXrDEV** [comment]
Thank you so much, my savior :D

**Comment by WanionCane** [comment]
I forgot to ask, which version? 1.7.10 or 1.10.2?

**Comment by HaXrDEV** [comment]
1.10.2 as i stated in the issue xD

**Comment by WanionCane** [comment]
I changed it a bit on the last version, could you try it? :)

**Comment by HaXrDEV** [comment]
Yes ill give it a try, thank you ;)
