### ISSUE TITLE
"registerNewCraftingIngredientsAsItemStacks"=true causing Thermal Foundation plates to appear in crafting tables.

### ISSUE THREAD

**Issue by Dreytac** [WanionCane/UniDict#80]
Enabling the "**registerNewCraftingIngredientsAsItemStacks**" option in UniDict is causing Thermal Foundation plates to be "crafted" in crafting tables upon opening the interfaces.

In the log file, I've found the following:
```
20729 [00:08:54] [main/ERROR] [jei/jei]: Recipe has no inputs. UniDict unidict:platetin_x1_size.0
20734 [00:08:54] [main/ERROR] [jei/jei]: Recipe has no inputs. UniDict unidict:platebronze_x1_size.0
20739 [00:08:54] [main/ERROR] [jei/jei]: Recipe has no inputs. UniDict unidict:platelead_x1_size.0
20744 [00:08:54] [main/ERROR] [jei/jei]: Recipe has no inputs. UniDict unidict:platecopper_x1_size.0
```
I originally thought it was an issue with Baubles and found [this issue](https://github.com/Azanor/Baubles/issues/233). Upon changing the option back to "false" the issue goes away, along with those lines in the log file.

Minecraft: v1.12.2
Forge: v14.23.1.2604
UniDict: v2.3.2
Log File: [fml-client-3.log](https://github.com/WanionCane/UniDict/files/1695493/fml-client-3.log)

![baubles](https://user-images.githubusercontent.com/861156/35810307-16ecb99a-0ad7-11e8-9ba3-64d3931ecf94.png)
![crafting_station](https://user-images.githubusercontent.com/861156/35810308-1732999c-0ad7-11e8-9bc0-36c49ad9bcec.png)

**Comment by WanionCane** [comment]
I will take a look, for now, it is better keep it off =P
