### ISSUE TITLE
Forestry genetic filter ingredients don't get unified

### ISSUE THREAD

**Issue by tornewuff** [WanionCane/UniDict#81]

**Comment by tornewuff** [comment]
Oops, hit the button very prematurely :)

With Unidict 2.3.2 set to keepOneEntry=true, Forestry 5.7.0.238, and Thermal Foundation, the (fairly recently added?) genetic filter item from forestry doesn't appear to get unified properly: it ends up needing two Forestry bronze gears as ingredients but there's no recipe to make them as all the gears were replaced by Thermal's. All the other forestry items appear to work fine.

**Comment by WanionCane** [comment]
UniDict doesn't change the recipe inputs.
on this case, I recommend you to open an issue on Forestry GitHub asking if
they could add support for OreDictionary for this Specific recipe.

**Comment by tornewuff** [comment]
Thanks; I realised this after filing this issue and forgot to come back and comment. ForestryMC/ForestryMC#1978
