### ISSUE TITLE
unidict compat with ExNihilo, etc

### ISSUE THREAD

**Issue by jmac460** [WanionCane/UniDict#82]
unidict is having a conflict with the following mods: BaseMetals, ExnihiloCreatio, and Thermal Foundation. When i go to load a world i get an error about 125 missing entries. 
![image](https://user-images.githubusercontent.com/34420502/36284418-32a36e2a-126d-11e8-86ac-23508bf0e132.png)

**Comment by jmac460** [comment]
Also, to be clear: the specific issues i am having aside from what is pictured: The unidict fails to correctly use those mods ores like they are supposed to. 

![image](https://user-images.githubusercontent.com/34420502/36284839-eb501602-126e-11e8-8452-46ca2b250d58.png)
![image](https://user-images.githubusercontent.com/34420502/36284842-ee5e4cd8-126e-11e8-985f-7142a0400af6.png)
These pictures show what i am referring to... The recipe should be 4 in a square, not a reverse 7. And the ores they should default to is the Ore Chunks, not the vanilla and Thermal Foundation ones.

**Comment by WanionCane** [comment]
sorry for the delay, about the first Issue, I think, you had a map before installing UniDict? if yes, may be it.
the second issue will be fixed on the next update that will be released soon.
