### ISSUE TITLE
Error in game output log

### ISSUE THREAD

**Issue by StephJ2Fan** [WanionCane/UniDict#83]
I keep seeing this error show up in my log after I close out the game.

18:08:13 | FML | main | error | Unable to parse dependency for mod 'simpleoregen' with dependency string 'after:advancedrocketry,appliedenergistics2,embers,forestry,fp,ic2,iceandfire,immersiveengineering,mekanism,techreborn,tconstruct'. The modId 'advancedrocketry,appliedenergistics2,embers,forestry,fp,ic2,iceandfire,immersiveengineering,mekanism,techreborn,tconstruct' is longer than the maximum of 64 characters.
-- | -- | -- | -- | --

**Comment by WanionCane** [comment]
this is probably a **[simpleoregen](https://minecraft.curseforge.com/projects/simple-ore-generation)** thing.
