### ISSUE TITLE
[Feature Request?] Unify Thermal Expansion and Immersive Engineering slag?

### ISSUE THREAD

**Issue by ghost** [WanionCane/UniDict#85]
I'm honestly not sure if this should be a feature or not, frankly. I noticed today that Thermal Expansion and Immersive Engineering both generate Slag, and both have the `crystalSlag` and `itemSlag` ore dict entries, but aren't interchangeable in recipes. Would that be something to integrate with UniDict? I'm honestly not sure if this would end up being overpowered, as it seems IE slag is way easier to create than TE slag, so that might make some recipes a bit too easy.

Anyways, just a thought.

**Comment by WanionCane** [comment]
sorry for the delay.
UniDict is intended to be used with metals, but this may be possible, I will take a look =)

**Comment by axieum** [comment]
I came here to note this as well. I've added the following entry the config, which works in the JEI main view, but doesn't physically change the recipes in Immersive Engineering:

```
S:customUnifiedResources <
        ...
        Slag:item|crystal
     >
```

Here is the entire config file: https://hastebin.com/valijoduqo.cfg

It definitely hides the duplicates in the JEI, but doesn't change the recipes.

**Comment by WanionCane** [comment]
sorry for the super late reply, so, the only way to do this, first, register both items on both ore dict entries, after this:

> S:customUnifiedResources <
>        ...
>       Slag:item|crystal
>     >

should work just fine =P

**Comment by axieum** [comment]
Cheers, will give it a go later!

**Comment by axieum** [comment]
I can't get it to work. Using the config I posted earlier, it will hide the other Slag items from JEI, but it hasn't changed the Slag in the IE recipes to output TE slag... 

This is with Thermal Foundation with highest priority, meaning Immersive Engineering machines should output Thermal Foundation slag.

**Comment by axieum** [comment]
Here's my updated configuration file: https://hastebin.com/siwivoneci.cfg
