### ISSUE TITLE
Blood Magic Support for 1.12.2

### ISSUE THREAD

**Issue by TechnoMysterio** [WanionCane/UniDict#86]
Blood Magic is in a fairly stable alpha release for 1.12.2, so updating integration for it's Alchemy Table recipes would be good.

**Comment by WanionCane** [comment]
the next update will have it =D

**Comment by WanionCane** [comment]
[UniDict-1.12.2-2.5](https://minecraft.curseforge.com/projects/unidict/files/2552250)
