### ISSUE TITLE
[Suggestion] Geolosys support?

### ISSUE THREAD

**Issue by neothiamin** [WanionCane/UniDict#87]
I'm trying to use Unidict with Geolosys, and I wanted to remove the ability to smelt Geolosys clusters into ingots. I tried using the CraftTweaker function to remove all Furnace recipes that result in an ingot, but that ended up removing dust to ingot recipes as well, which I did not want. I tried adding "ore" to the blacklist as instructed in the wiki, but it still was removing recipes that involved both ore and dusts. Is Geolosys not supported? My config file is this: https://pastebin.com/NMUhH5pe and the script I was using is this: https://pastebin.com/52ueE8BC. Am I doing something wrong or does Geolosys integration need to be added for this to function like I want it?

**Comment by WanionCane** [comment]
for now, I this is not possible.
maybe adding another filter will allow you to do this kind of recipe remossion.
so, for now, I recommend you to remove the recipes manually.
