### ISSUE TITLE
More support

### ISSUE THREAD

**Issue by blockbreaker1361** [WanionCane/UniDict#88]
Please add in EnderIO support. This mod causes crashes with it and it needs to be updated.

**Comment by WanionCane** [comment]
the integration is coming soon.
it shouldn't crash ender io, I tried here on All the Mods and it is working fine.
could you provide me a crash log?

**Comment by WanionCane** [comment]
[UniDict-1.12.2-2.5](https://minecraft.curseforge.com/projects/unidict/files/2552250)
