### ISSUE TITLE
Recipes by UniDict not being removed by CraftTweaker

### ISSUE THREAD

**Issue by TheDeviantCrafter** [WanionCane/UniDict#89]
When disabling most items with CraftTweaker, the recipe and the corrosponding JEI entry are removed as expected. Recipes added by UniDict, however, do not get removed.

**Reproduction steps:**

1. Install Immersive Engineering, Thermal Foundation., Unidict, and CraftTweaker

2. Create a script file with the following code:

`recipes.removeShapeless(<thermalfoundation:material:32>);`

3. Reload the game and check the recipe of Thermal Foundation's iron plate

**What I expected to happen:**

Both recipes for the iron plate would be removed. 

**What actually happened:**

Both recipes are still enabled, even though the script is supposed to remove them.

**Versions:**

Minecraft: 1.12.2
Forge: 14.23.2.2654
CoFH Core: 4.3.11.6
CoFH World: 1.1.1.12
CraftTweaker: 4.1.6
JEI: 4.8.5.159
MTLib: 3.0.4
Thermal Foundation: 2.3.11.8
UniDict: 2.4c
WanionLib: 1.5

![image](https://user-images.githubusercontent.com/18755309/38763223-6a1a44ac-3f5c-11e8-9a08-aa6a92b1e401.png)

**Comment by TheDeviantCrafter** [comment]
Also posted this to CraftTweaker's issues page: https://github.com/CraftTweaker/CraftTweaker/issues/518

**Comment by WanionCane** [comment]
this is not a CraftTweaker Issue, the reason for this is because UniDict adds it's recipes waay after CraftTweaker removes recipes.
there is a config file in UniDict.cfg to remove these recipes added by UniDict
"S:recipeToRemoveList"
