### ISSUE TITLE
Machines only accept a single ore type when keepOneEntry is true

### ISSUE THREAD

**Issue by Ionaru** [WanionCane/UniDict#92]
**The issue**
Machines like the pulveriser from Thermal Expansion, do not accept any ores except the Thermal Foundation ones when the keepOneEntry option is true.
I enabled this feature so user would not get the confusing recipes anymore with all the changing oredict items in them, but I did not expect machines to stop working with different ores.

**Version information**
* Minecraft 1.7.10
* Forge 10.13.4.1614
* UniDict 1.7.10-2.9.2

**Comment by WanionCane** [comment]
well, I know this may sound weird, but this is the inteended behavior,
if a machine is expecting an OreDitionary, but a given input isn't part of that OreDict anymore, so...  obviously it will not accept.
the only solution I see for this is turning off keepOneEntry.

**Comment by Ionaru** [comment]
Would it be possible to add the ores to the machine input, without using the ore dictionary? (Feature request for this mod)
It is possible to do through CraftTweaker / ModTweaker, but I'd like to avoid having to manually find, create and maintain those recipes.
