### ISSUE TITLE
Help disabling UniDict recipes for Thermal Foundation gears

### ISSUE THREAD

**Issue by TheDeviantCrafter** [WanionCane/UniDict#94]
I've successfully used the "recipesToRemoveList" section of the config to remove UniDict recipes for Thermal Foundation's dust blend. I'd like to do the same for Thermal Foundation gears, but it doesn't seem to be working.

Specifically, I'd like to remove the recipes for copper, tin, iron and bronze gears. I removed the crafting recipes for all of the gears, and the four I mentioned are the only ones that still have crafting recipes.

This is the relevant section of my config:

```
S:recipeToRemoveList <
        unidict:dustconstantan_x2_size.2
        unidict:dustinvar_x3_size.3
        unidict:dustbronze_x4_size.4
        unidict:dustelectrum_x2_size.2
	unidict:geariron_x1_shape. a aba a 
	unidict:gearcopper_x1_shape. a aaa a 
	unidict:geartin_x1_shape. a aba a 
	unidict:gearbronze_x1_shape. a aba a 
     >
```

The four gears are still there, though. Here's a screenshot from JEI:

![image](https://user-images.githubusercontent.com/18755309/39964006-34a510b8-5640-11e8-89aa-a9322ff4f166.png)

Also, here's the entire config file (changed to a .txt file so Github would support it):

[UniDict.txt](https://github.com/WanionCane/UniDict/files/1998112/UniDict.txt)

What I've tried so far:

- Adding a space after the end of the recipe name string

- Removing the space from the recipe string

- Putting the string on quotes (as seen in the screenshot in issue #44)

All three times the recipes stayed after restarting the pack.

**Versions:**

Minecraft: 1.12

Forge: 14.23.3.2673

Unidict: 2.5b

**Comment by WanionCane** [comment]
on this case, there is a better alternative for "recipesToRemoveList".

but, only use it if you really want to remove all the gears recipes, checkout this CraftTweaker command:
> mods.unidict.removalByKind.get("Crafting").remove("gear");

basically, it is an all in one command, that will remove all "gear" recipes (could be ingot, block, nugget, and so on...).

for a better explanation about what it does, checkout [this](../wiki/crafttweaker-support#removal-by-kind) wiki page.

**Comment by Grishord** [comment]
Where do we add this line

`mods.unidict.removalByKind.get("Crafting").remove("gear");`

 to make it ignore the gear recipes so we can craft the ones from thermal expansion?

**Comment by WanionCane** [comment]
it is a CraftTweaker command, so you just need to create a .zs script and put it on it.
but, this command will remove **all** the gear recipes.
also, you forgot to add "quotes" on the "S:recipeToRemoveList" entries that has a space on the end;
it should looks like this:

> S:recipeToRemoveList
> 	unidict:dustconstantan_x2_size.2
> 	unidict:dustinvar_x3_size.3
> 	unidict:dustbronze_x4_size.4
> 	 unidict:dustelectrum_x2_size.2
> 	"unidict:geariron_x1_shape. a aba a "
> 	"unidict:gearcopper_x1_shape. a aaa a "
> 	"unidict:geartin_x1_shape. a aba a "
> 	"unidict:gearbronze_x1_shape. a aba a "
>      >
