### ISSUE TITLE
Thermal Expansion Redstone Furnace

### ISSUE THREAD

**Issue by NielsPilgaard** [WanionCane/UniDict#95]
Hey hey.

The Redstone Furnace from Thermal Expansion suddenly doesn't get its output unified by UniDict anymore.

Forge 1.12.2-14.23.2673
UniDict-1.12.2-2.5b

**Comment by WanionCane** [comment]
thanks for letting me know, I will take a look =)

**Comment by NielsPilgaard** [comment]
Oh it was my mistake. I had added `thaumcraft` and `biomesoplenty` to the bottom of the `ownerOfEverything` config, reverting that fixed the Redstone Furnace.
