### ISSUE TITLE
Errors on startup: NoSuchField recipeMapPress and something about ThermalExpansion

### ISSUE THREAD

**Issue by gw2princeps** [WanionCane/UniDict#96]
Hi there, 

there seems to be an error on startup. 
[ErrorOnly](https://gist.github.com/SpatiumPrinceps/20c5a7ec4e42b6fbc88d64dd00018a15)
[FullLog](https://gist.github.com/SpatiumPrinceps/b484dcd6b2c4cb739d1c0d6353857128)

Using thermal expansion version 5.4.2.27

**Comment by WanionCane** [comment]
[this](https://minecraft.curseforge.com/projects/unidict/files/2563162) should fix it.
