### ISSUE TITLE
[Suggestion] Extend Embers integration to support Soot

### ISSUE THREAD

**Issue by luke-bravenboer** [WanionCane/UniDict#97]
[Soot](https://minecraft.curseforge.com/projects/soot) is a great little addon mod for embers, adding some nifty improvements & enhancements, such as machine upgrades, crafttweaker support, and much more. However, it breaks the unidict embers integration. After installing Soot, the Stamper from embers has no longer been respecting my unidict configuration & has been producing embers ingots & plates (rather than the expected thermal foundation variants).

It's not overly surprising, as Soot sounds to be making some fundamental changes to the base embers machines- hopefully not so much so that you can't extend your embers integration module to support it? :)

**Comment by WanionCane** [comment]
sorry for the delay.. =(
I will see what I can do, but no promises.

**Comment by luke-bravenboer** [comment]
No worries, I mean we can always adjust it manually with crafttweaker + some extra effort- just wanted to make you aware!

**Comment by ElektroKill** [comment]
I am unable to reproduce this problem with the latest version of UniDict, Embers, and Soot.
