### ISSUE TITLE
[1.12.2] Mekanism Sulfur Dust

### ISSUE THREAD

**Issue by Draskh** [WanionCane/UniDict#99]
UniDict does not replace the Sulfur Dust of Mekanism with right one of Thermal Foundation.
![2018-06-19_14 43 02](https://user-images.githubusercontent.com/26455012/41598055-683f75ce-73cf-11e8-8851-1dbc54084b93.png)

**Comment by WanionCane** [comment]
the next version will have support for Chemical Injection Chamber =)

**Comment by Draskh** [comment]
That's nice. Thank you.
